-- Full Seed Data for Tawakkal Paint Store
-- Clear and reset
DELETE FROM products;

-- ------------------------------------------------------------------------------------------------
-- BERGER PRODUCTS (47)
-- ------------------------------------------------------------------------------------------------
INSERT INTO products (name, brand, category, sub_category, description, image_url, price_quarter, price_gallon, price_drum, in_stock) VALUES
('Berger Advance Polyurethane 2k Clear', 'Berger', 'industrial', 'wood_metal', 'High performance 2K clear polyurethane finish', '/images/products/berger/Advance Polyurethane 2k Clear.webp', 3500, 12000, 48000, true),
('Berger Advance Polyurethane 2k Hardener', 'Berger', 'industrial', 'wood_metal', 'Hardener for 2K polyurethane systems', '/images/products/berger/Advance Polyurethane 2k Hardener.webp', 3200, 11000, 0, true),
('Berger Advance Polyurethane 2k Matt Clear', 'Berger', 'industrial', 'wood_metal', 'Matt finish 2K clear polyurethane', '/images/products/berger/Advance Polyurethane 2k Matt Clear.webp', 3600, 12500, 50000, true),
('Berger Advance Polyurethane 2k Sanding Sealer', 'Berger', 'industrial', 'wood_metal', 'Sanding sealer for 2K PU systems', '/images/products/berger/Advance Polyurethane 2k Sanding Sealer.webp', 2800, 9500, 38000, true),
('Berger Advance Polyurethane 2k Thinner', 'Berger', 'industrial', 'wood_metal', 'Specialized thinner for 2K PU paints', '/images/products/berger/Advance Polyurethane 2k Thinner.webp', 1200, 4200, 0, true),
('Berger Aluminum Paint', 'Berger', 'decorative', 'wood_metal', 'Reflective aluminum paint for protection', '/images/products/berger/Aluminum-Paint.webp', 1100, 3800, 17800, true),
('Berger Apexior No. 1', 'Berger', 'industrial', 'exterior', 'Protective coating for high temperature surfaces', '/images/products/berger/Apexior-No-1.webp', 4500, 16000, 72000, true),
('Berger Apexior No. 3', 'Berger', 'industrial', 'exterior', 'Anti-corrosive coating for wet surfaces', '/images/products/berger/Apexior-No_3.webp', 4700, 16500, 74000, true),
('Berger Chlorinated Rubber Base Paint', 'Berger', 'industrial', 'exterior', 'Chemical and water resistant rubber base paint', '/images/products/berger/Chlorinated-Rubber-Base-Paint.webp', 3800, 13500, 60000, true),
('Berger Duxbak', 'Berger', 'decorative', 'exterior', 'Water repellent masonry protection', '/images/products/berger/Duxbak.webp', 1500, 5200, 23000, true),
('Berger Plastron Wall Primer', 'Berger', 'decorative', 'accessories', 'High quality water-based wall primer', '/images/products/berger/PLASTRON WALL PRIMER.webp', 650, 2200, 10200, true),
('Berger Red Oxide Primer', 'Berger', 'decorative', 'wood_metal', 'Anti-rust primer for metal surfaces', '/images/products/berger/Red-Oxide-Primer.webp', 850, 2900, 13500, true),
('Berger SPD Premium Putty', 'Berger', 'decorative', 'accessories', 'White cement based premium wall putty', '/images/products/berger/SPD Premium Putty - White Cement Based.webp', 800, 2700, 0, true),
('Berger SPD Repaint Putty', 'Berger', 'decorative', 'accessories', 'White cement based repaint putty', '/images/products/berger/SPD Repaint Putty - White Cement Based.webp', 750, 2500, 0, true),
('Berger Synthetic Under Coat', 'Berger', 'decorative', 'wood_metal', 'Quality undercoat for smooth finish', '/images/products/berger/Synthetic-Under-Coat.webp', 950, 3200, 15000, true),
('Berger Top Super Primer Plus', 'Berger', 'decorative', 'accessories', 'Premium water based primer plus', '/images/products/berger/Top Super Primer Plus water base priemer.webp', 700, 2400, 11000, true),
('Berger Weather Coat Exterior Putty', 'Berger', 'decorative', 'accessories', 'Durable exterior grade wall putty', '/images/products/berger/Weather Coat Exterior Putty - White Cement Based.webp', 900, 3100, 0, true),
('Berger Allrounder Matt Enamel', 'Berger', 'decorative', 'wood_metal', 'Multi-surface matt enamel finish', '/images/products/berger/allrounder matt enamel (wood, metal & wall).webp', 1850, 6400, 29000, true),
('Berger Elegance Emulsion', 'Berger', 'decorative', 'interior', 'Premium interior emulsion for elegant walls', '/images/products/berger/elegance emulsion.png', 1650, 5600, 26000, true),
('Berger Elegance Interior Putty', 'Berger', 'decorative', 'accessories', 'Finely textured interior wall putty', '/images/products/berger/elegance enterior putty.webp', 720, 2500, 0, true),
('Berger Elegance Silk Finish', 'Berger', 'decorative', 'interior', 'Luxurious silk-like finish for interiors', '/images/products/berger/elegance silk finish.png', 1800, 6200, 28500, true),
('Berger Elegance Water Base Primer', 'Berger', 'decorative', 'accessories', 'Breathable water based primer', '/images/products/berger/elegance water base priemer.webp', 600, 2100, 9500, true),
('Berger NU Emulsion', 'Berger', 'decorative', 'interior', 'Standard quality wall emulsion', '/images/products/berger/nu emulsion.png', 1350, 4600, 21500, true),
('Berger NU Enamel', 'Berger', 'decorative', 'wood_metal', 'Durable enamel for wood and metal', '/images/products/berger/nu enamel.png', 1700, 5800, 27000, true),
('Berger NU Putty', 'Berger', 'decorative', 'accessories', 'Standard interior wall putty', '/images/products/berger/nu putty.webp', 580, 1950, 0, true),
('Berger NU Water Base Primer', 'Berger', 'decorative', 'accessories', 'Economic water based primer', '/images/products/berger/nu water base primer.webp', 520, 1800, 8500, true),
('Berger Semi Plastic Emulsion', 'Berger', 'decorative', 'interior', 'Cost-effective semi plastic finish', '/images/products/berger/semi plastic emulsion.png', 1150, 3900, 18000, true),
('Berger Silk Emulsion', 'Berger', 'decorative', 'interior', 'Smooth silk emulsion paint', '/images/products/berger/silk emulsion.png', 1550, 5300, 24500, true),
('Berger SPD Wall Putty', 'Berger', 'decorative', 'accessories', 'Cement based wall putty', '/images/products/berger/spd wall putty.webp', 650, 2200, 0, true),
('Berger Super Gloss Enamel', 'Berger', 'decorative', 'wood_metal', 'High gloss premium enamel', '/images/products/berger/super gloss enamel.png', 1900, 6500, 30000, true),
('Berger Superior Matt Finish', 'Berger', 'decorative', 'interior', 'Flat superior matt wall finish', '/images/products/berger/superior matt finish.png', 1450, 4900, 22500, true),
('Berger Top Super Emulsion', 'Berger', 'decorative', 'interior', 'High performance top emulsion', '/images/products/berger/top super emulsion.webp', 1500, 5100, 23500, true),
('Berger Top Super Putty', 'Berger', 'decorative', 'accessories', 'Premium grade wall filling putty', '/images/products/berger/top super putty.webp', 700, 2400, 0, true),
('Berger VIP Weather Coat', 'Berger', 'decorative', 'exterior', 'Premium weather resistant exterior paint', '/images/products/berger/vip weather coat.webp', 1850, 6400, 29000, true),
('Berger Weather Coat Exterior Putty', 'Berger', 'decorative', 'accessories', 'Weather resistant exterior putty', '/images/products/berger/weather coat exterior putty.webp', 850, 2900, 0, true),
('Berger Weather Coat Glow 365', 'Berger', 'decorative', 'exterior', 'All-year protective exterior coating', '/images/products/berger/weather coat glow 365.webp', 1900, 6600, 31000, true),
('Berger Weather Coat Pure Seal', 'Berger', 'decorative', 'exterior', 'Advanced pure seal exterior protection', '/images/products/berger/weather coat pure seal.webp', 2000, 6900, 32000, true),
('Berger Weather Pro Exterior Primer', 'Berger', 'decorative', 'accessories', 'Professional grade exterior primer', '/images/products/berger/weather pro exterior primer.webp', 750, 2600, 12000, true),
('Berger Weather Pro Exterior Putty', 'Berger', 'decorative', 'accessories', 'High durability exterior putty', '/images/products/berger/weather pro exterior putty.webp', 820, 2800, 0, true),
('Berger Weather Pro', 'Berger', 'decorative', 'exterior', 'Professional exterior weather shield', '/images/products/berger/weather pro.webp', 1750, 6000, 28000, true),
('Berger Weathercoat Sand Finish Primer', 'Berger', 'decorative', 'accessories', 'Textured sand finish primer', '/images/products/berger/weathercoat Sand Finish Primer.webp', 800, 2750, 0, true),
('Berger Woodpro Special Thinner', 'Berger', 'decorative', 'wood_metal', 'Thinner for Woodpro lacquer systems', '/images/products/berger/woodpr speciel thiner.webp', 1100, 3800, 0, true),
('Berger Woodpro Gloss Lacquer', 'Berger', 'decorative', 'wood_metal', 'High gloss wood lacquer', '/images/products/berger/woodpro gloss lacquer.webp', 2300, 7800, 0, true),
('Berger Woodpro Matt Lacquer', 'Berger', 'decorative', 'wood_metal', 'Premium matt wood lacquer', '/images/products/berger/woodpro matt laquer.webp', 2200, 7500, 0, true),
('Berger Woodpro PU Lacquer', 'Berger', 'decorative', 'wood_metal', 'Polyurethane wood lacquer', '/images/products/berger/woodpro pu lacquer.webp', 2600, 8800, 0, true),
('Berger Woodpro Sanding Sealer', 'Berger', 'decorative', 'wood_metal', 'High fill sanding sealer', '/images/products/berger/woodpro sanding sealer.webp', 1900, 6500, 0, true),
('Berger Woodpro Synthetic Clear Varnish', 'Berger', 'decorative', 'wood_metal', 'Durable clear wood varnish', '/images/products/berger/woodpro synthetic clear varnish.webp', 1800, 6200, 0, true);

-- ------------------------------------------------------------------------------------------------
-- GOBI'S PRODUCTS (37)
-- ------------------------------------------------------------------------------------------------
INSERT INTO products (name, brand, category, sub_category, description, image_url, price_quarter, price_gallon, price_drum, in_stock) VALUES
('Gobis Clear Lacquer', 'Gobi''s', 'decorative', 'wood_metal', 'High quality clear lacquer finish', '/images/products/gobis/clear_lacquer-removebg-preview.png', 1950, 6700, 0, true),
('Gobis Gold Weather Guard', 'Gobi''s', 'decorative', 'exterior', 'Premium weather guard protection', '/images/products/gobis/gobi''s gold weather guard.png', 1850, 6300, 29000, true),
('Gobis Summer Weather Shield', 'Gobi''s', 'decorative', 'exterior', 'Advanced summer protection shield', '/images/products/gobis/gobi''s-Summer-Weather-Shield.png', 1750, 6000, 27500, true),
('Gobis Aqueous Matt Finish', 'Gobi''s', 'decorative', 'interior', 'Superior aqueous matt wall finish', '/images/products/gobis/Gobis-Aqueous-Matt-Finish-253x253-removebg-preview.png', 1450, 4950, 23000, true),
('Gobis Aqueous Wall Sealer', 'Gobi''s', 'decorative', 'accessories', 'High performance wall sealer', '/images/products/gobis/gobis-aqueous-wall-sealer-253x253-removebg-preview.png', 750, 2600, 12000, true),
('Gobis Gloss Enamel', 'Gobi''s', 'decorative', 'wood_metal', 'Premium high gloss enamel finish', '/images/products/gobis/Gobis-Gloss-Enamel-253x253-removebg-preview.png', 1800, 6200, 28500, true),
('Gobis Gold Aqueous Matt Finish', 'Gobi''s', 'decorative', 'interior', 'Elite gold aqueous matt finish', '/images/products/gobis/Gobis-Gold-Aqueous-Matt-Finish-253x253-removebg-preview.png', 1600, 5500, 25500, true),
('Gobis Gold Enamel', 'Gobi''s', 'decorative', 'wood_metal', 'Elite gold series enamel', '/images/products/gobis/Gobis-Gold-Enamel-253x253-removebg-preview.png', 1950, 6700, 31000, true),
('Gobis Gold Red Oxide Primer', 'Gobi''s', 'decorative', 'wood_metal', 'Elite anti-rust metal primer', '/images/products/gobis/Gobis-Gold-Red-Oxide-Primer-253x253-removebg-preview.png', 1050, 3600, 16500, true),
('Gobis Gold Undercoat', 'Gobi''s', 'decorative', 'wood_metal', 'Elite series wood/metal undercoat', '/images/products/gobis/Gobis-Gold-Undercoat-253x253-removebg-preview.png', 1100, 3800, 17500, true),
('Gobis Gold Wall Emulsion', 'Gobi''s', 'decorative', 'interior', 'Elite series premium wall emulsion', '/images/products/gobis/Gobis-GOld-Wall-Emulsion-253x253-removebg-preview.png', 1700, 5800, 27000, true),
('Gobis Gold Wall Putty', 'Gobi''s', 'decorative', 'accessories', 'Elite series fine wall putty', '/images/products/gobis/Gobis-Gold-Wall-Putty-253x253-removebg-preview.png', 780, 2650, 0, true),
('Gobis Premium Accessories', 'Gobi''s', 'decorative', 'accessories', 'Selection of premium paint tools', '/images/products/gobis/Gobis-Premium-Accessories.png', 0, 0, 0, true),
('Gobis Red Oxide Primer Plus', 'Gobi''s', 'decorative', 'wood_metal', 'Enhanced red oxide primer', '/images/products/gobis/Gobis-Red-Oxide-Primer-253x253-removebg-preview (1).png', 980, 3350, 0, true),
('Gobis Red Oxide Primer', 'Gobi''s', 'decorative', 'wood_metal', 'Standard red oxide primer', '/images/products/gobis/Gobis-Red-Oxide-Primer-253x253-removebg-preview.png', 950, 3300, 0, true),
('Gobis Silksheen Emulsion', 'Gobi''s', 'decorative', 'interior', 'Luxurious silksheen interior finish', '/images/products/gobis/Gobis-Silksheen-Emulsion-253x253-removebg-preview.png', 1750, 6000, 28000, true),
('Gobis Silverline Emulsion', 'Gobi''s', 'decorative', 'interior', 'Silverline series wall emulsion', '/images/products/gobis/Gobis-Silverline-Emulsion-253x253.png', 1400, 4800, 22000, true),
('Gobis Silverline Enamel', 'Gobi''s', 'decorative', 'wood_metal', 'Silverline series gloss enamel', '/images/products/gobis/Gobis-Silverline-Enamel-253x253.png', 1650, 5700, 26500, true),
('Gobis Silverline Wall Putty', 'Gobi''s', 'decorative', 'accessories', 'Silverline series wall putty', '/images/products/gobis/Gobis-Silverline-Wall-Putty-253x253.png', 680, 2300, 0, true),
('Gobis Silverline Wall Sealer', 'Gobi''s', 'decorative', 'accessories', 'Silverline series wall sealer', '/images/products/gobis/Gobis-Silverline-Wall-Sealer-580x580.png', 720, 2450, 11000, true),
('Gobis Sona Lapi', 'Gobi''s', 'decorative', 'interior', 'Special textured decorative finish', '/images/products/gobis/Gobis-Sona-Lapi-253x253-removebg-preview.png', 1850, 6400, 29500, true),
('Gobis Summer Superior Emulsion', 'Gobi''s', 'decorative', 'interior', 'Heat resistant summer emulsion', '/images/products/gobis/Gobis-Summer-Suprior-Emulsion.png', 1550, 5300, 24500, true),
('Gobis Summer Wall Filling', 'Gobi''s', 'decorative', 'accessories', 'Summer grade wall filler', '/images/products/gobis/Gobis-Summer-Wall-Filling.png', 750, 2550, 0, true),
('Gobis Summer Wall Sealer', 'Gobi''s', 'decorative', 'accessories', 'Summer grade wall sealer', '/images/products/gobis/Gobis-Summer-Wall-Sealer.png', 780, 2650, 12000, true),
('Gobis Valmate Superior Emulsion', 'Gobi''s', 'decorative', 'interior', 'Value series superior emulsion', '/images/products/gobis/Gobis-Valmate-Superior-Emulsion.png', 1350, 4600, 21000, true),
('Gobis Valmate Wall Filling', 'Gobi''s', 'decorative', 'accessories', 'Value series wall filler', '/images/products/gobis/Gobis-Valmate-Wall-Filling.png', 650, 2200, 0, true),
('Gobis Valmate Wall Sealer', 'Gobi''s', 'decorative', 'accessories', 'Value series wall sealer', '/images/products/gobis/Gobis-valmate-Wall-Sealer.png', 680, 2350, 10500, true),
('Gobis Valmate Weather Shield', 'Gobi''s', 'decorative', 'exterior', 'Value series weather protector', '/images/products/gobis/Gobis-Valmate-Weather-Shield.png', 1500, 5200, 24000, true),
('Gobis Wall Primer Sealer', 'Gobi''s', 'decorative', 'accessories', 'Combo primer and sealer', '/images/products/gobis/Gobis-Wall-Primer-Sealer.png', 740, 2500, 11500, true),
('Gobis Weather Protector', 'Gobi''s', 'decorative', 'exterior', 'Standard weather protection coating', '/images/products/gobis/Gobis-Weather Protector.png', 1650, 5700, 26500, true),
('Gobis Gold Eggshell Matt Finish', 'Gobi''s', 'decorative', 'interior', 'Elite eggshell finish wall paint', '/images/products/gobis/gobis_gold_eggshell-matt-finish-253x253-removebg-preview.png', 1650, 5600, 26000, true),
('Gobis Heat Flex Sealant', 'Gobi''s', 'decorative', 'waterproofing', 'Flexible heat resistant sealant', '/images/products/gobis/heat flex sealent.png', 2500, 8500, 0, true),
('Gobis Wood Finish / Metal Finish', 'Gobi''s', 'decorative', 'wood_metal', 'Dual surface wood and metal finish', '/images/products/gobis/wood_finish__metal_finish-removebg-preview.png', 1900, 6500, 30000, true),
('Gobis Wood Sealer', 'Gobi''s', 'decorative', 'wood_metal', 'High penetration wood sealer', '/images/products/gobis/wood_sealer-removebg-preview.png', 1750, 6000, 0, true),

-- ------------------------------------------------------------------------------------------------
-- DIAMOND PRODUCTS (46)
-- ------------------------------------------------------------------------------------------------
INSERT INTO products (name, brand, category, sub_category, description, image_url, price_quarter, price_gallon, price_drum, in_stock) VALUES
('Diamond Ace Acrylic Plastic Emulsion', 'Diamond', 'decorative', 'interior', 'Premium acrylic plastic emulsion', '/images/products/diamond/ace acrylic-plastic-emulsion.webp', 1450, 4900, 22500, true),
('Diamond Ace Durasilk Emulsion', 'Diamond', 'decorative', 'interior', 'Smooth Durasilk interior finish', '/images/products/diamond/ace Durasilk emulsion.webp', 1600, 5500, 25500, true),
('Diamond Ace Extra Smooth Filler Putty', 'Diamond', 'decorative', 'accessories', 'Extra smooth wall filler putty', '/images/products/diamond/ace extra-smooth-filler-putty_4a8bdf80-2382-4792-977f-0afc147edf6b.webp', 750, 2600, 0, true),
('Diamond Ace Gloss Lacquer Timberlac', 'Diamond', 'decorative', 'wood_metal', 'Glossy Timberlac wood finish', '/images/products/diamond/ace Gloss-lacquer-Timberlac_acfb771b-f4b1-40cc-aa0b-1f42246bc090.webp', 2200, 7500, 0, true),
('Diamond Ace Hi Sparkle Metallic', 'Diamond', 'decorative', 'interior', 'Sparkling metallic decorative finish', '/images/products/diamond/ace Hi sparkle metalic_087a2ef0-925d-43a8-9d04-c36e344d4990.webp', 1850, 6300, 0, true),
('Diamond Ace Matt Enamel', 'Diamond', 'decorative', 'wood_metal', 'Smooth matt enamel for different surfaces', '/images/products/diamond/ace matt enamel.webp', 1700, 5800, 27000, true),
('Diamond Ace Matt Lacquer Timberlac', 'Diamond', 'decorative', 'wood_metal', 'Matt Timberlac wood finish', '/images/products/diamond/ace Matt-lacquer-Timberlac_04b30648-d91a-4de4-bbd9-b94c984bf1c7.webp', 2100, 7200, 0, true),
('Diamond Ace PU Lacquer Timberlac', 'Diamond', 'decorative', 'wood_metal', 'Polyurethane Timberlac wood finish', '/images/products/diamond/ace Polyurethance-lacquer-Timberlac_5b782b09-4294-44bd-8c05-8da68a69aa5e.webp', 2500, 8500, 0, true),
('Diamond Ace Premium Thinner', 'Diamond', 'decorative', 'accessories', 'High quality paint thinner', '/images/products/diamond/ace premiumThiner_296c37df-e47f-4f23-a5bf-aaba91cbdcf8.webp', 1100, 3800, 0, true),
('Diamond Ace Sanding Sealer Timberlac', 'Diamond', 'decorative', 'wood_metal', 'Timberlac sanding sealer', '/images/products/diamond/ace sanding-sealer-Timberlac_7359fea6-d8d3-4e6b-b135-e380506f407b.webp', 1800, 6200, 0, true),
('Diamond Ace Soft Metallic', 'Diamond', 'decorative', 'interior', 'Soft metallic decorative paint', '/images/products/diamond/ace soft metalic.webp', 1750, 6000, 0, true),
('Diamond Ace Super Gloss Enamel', 'Diamond', 'decorative', 'wood_metal', 'Superior high gloss enamel', '/images/products/diamond/ace super gloss enamel.webp', 1900, 6500, 30000, true),
('Diamond Ace Super Sheesha Putty', 'Diamond', 'decorative', 'accessories', 'Ultra-smooth Sheesha wall putty', '/images/products/diamond/ace super Sheeshaputty_8ff351af-4fb6-4ecf-a9b4-f383c05307aa.webp', 820, 2800, 0, true),
('Diamond Ace Timberlac Clear Varnish', 'Diamond', 'decorative', 'wood_metal', 'Clear Timberlac wood varnish', '/images/products/diamond/ace timberlac clear_varnish.webp', 1850, 6300, 0, true),
('Diamond Ace Timberlac Wood Stains', 'Diamond', 'decorative', 'wood_metal', 'Range of Timberlac wood stains', '/images/products/diamond/ace timberlac---wood-stains.webp', 1500, 5100, 0, true),
('Diamond Ace Water Based Primer', 'Diamond', 'decorative', 'accessories', 'Quality water based wall primer', '/images/products/diamond/ace water-based-primer.webp', 650, 2250, 10500, true),
('Diamond Ace Weather Defender', 'Diamond', 'decorative', 'exterior', 'Outdoor weather shield protection', '/images/products/diamond/ace weather defender.webp', 1750, 6000, 28000, true),
('Diamond Ace Flexi Primer', 'Diamond', 'decorative', 'accessories', 'Flexible wall primer coating', '/images/products/diamond/AceFlexiprimer_68b92dcf-b2dc-4299-8666-44c8af138854.webp', 780, 2700, 12500, true),
('Diamond Diamond Enamel', 'Diamond', 'decorative', 'wood_metal', 'Classic Diamond series enamel', '/images/products/diamond/enamel.png', 1750, 5900, 27500, true),
('Diamond Everlast High Gloss Enamel', 'Diamond', 'decorative', 'wood_metal', 'Everlast series high gloss finish', '/images/products/diamond/everlast high gloss enamel.webp', 1850, 6300, 29500, true),
('Diamond Everlast Weather Proof', 'Diamond', 'decorative', 'exterior', 'Everlast all-weather protection', '/images/products/diamond/Everlast-Weather-Proof.webp', 1900, 6500, 30500, true),
('Diamond Interior Overall Texture', 'Diamond', 'decorative', 'interior', 'Decorative interior wall texturing', '/images/products/diamond/interior overall texture.webp', 1600, 5500, 25000, true),
('Diamond Matt Finish Inner', 'Diamond', 'decorative', 'interior', 'Premium Diamond series matt finish', '/images/products/diamond/Matt-Finish-Inner-630x630.png', 1650, 5650, 26000, true),
('Diamond Overall Aluminum Silver', 'Diamond', 'decorative', 'wood_metal', 'Aluminum silver protective paint', '/images/products/diamond/overall aluminum silver_2e53ad9f-0d4b-4698-9906-bd4ec05a3e4b.webp', 1200, 4100, 19500, true),
('Diamond Overall High Gloss Enamel', 'Diamond', 'decorative', 'wood_metal', 'Professional high gloss enamel', '/images/products/diamond/overall high gloss enamel.webp', 1800, 6150, 28500, true),
('Diamond Overall Metallic', 'Diamond', 'decorative', 'interior', 'Metallic series decorative finish', '/images/products/diamond/overall Metallic_4a2aed52-6c7c-4333-8fd4-6b9a28539b5b.webp', 1700, 5800, 0, true),
('Diamond Overall Paint Remover', 'Diamond', 'decorative', 'accessories', 'Strong stripping paint remover', '/images/products/diamond/overall paintremover_c194d12d-0970-4148-b03f-8f5c667d2d40.webp', 1500, 5100, 0, true),
('Diamond Overall Plasticcoat Special Shade', 'Diamond', 'decorative', 'interior', 'Special shade plasticcoat emulsion', '/images/products/diamond/overall plasticcoat emulsion speciel shade.webp', 1450, 4900, 22800, true),
('Diamond Overall Plasticcoat Emulsion', 'Diamond', 'decorative', 'interior', 'Standard plasticcoat wall emulsion', '/images/products/diamond/overall plasticcoat emulsion.webp', 1350, 4600, 21500, true),
('Diamond Overall Primer Filler Putty', 'Diamond', 'decorative', 'accessories', 'Dual purpose primer and filler', '/images/products/diamond/overall primerfiller putty_e88f82b7-caf7-4294-b7af-f487bd48bf35.webp', 850, 2900, 0, true),
('Diamond Overall Super Emulsion', 'Diamond', 'decorative', 'interior', 'Performance super wall emulsion', '/images/products/diamond/overall super emulsion.webp', 1500, 5150, 24000, true),
('Diamond Overall Thinner', 'Diamond', 'decorative', 'accessories', 'Standard multi-purpose thinner', '/images/products/diamond/overall thinner.webp', 950, 3250, 0, true),
('Diamond Overall Wall Sealer', 'Diamond', 'decorative', 'accessories', 'Effective interior wall sealer', '/images/products/diamond/overall wallsealer_2ff76c33-b42f-4c79-bc32-fa8caf75f545.webp', 720, 2450, 11500, true),
('Diamond Overll High Gloss Enamel', 'Diamond', 'decorative', 'wood_metal', 'High gloss series enamel', '/images/products/diamond/overll hgh gloss enamel.webp', 1800, 6200, 29000, true),
('Diamond Plastic Emulsion', 'Diamond', 'decorative', 'interior', 'Classic plastic wall emulsion', '/images/products/diamond/plastic emulsion.png', 1300, 4400, 20500, true),
('Diamond Plastic Primer Sealer', 'Diamond', 'decorative', 'accessories', 'Combined plastic primer and sealer', '/images/products/diamond/plastic priemer sealer.png', 680, 2350, 11000, true),
('Diamond Plastic Emulsion Special Shade', 'Diamond', 'decorative', 'interior', 'Bespoke shade plastic emulsion', '/images/products/diamond/Plastic-Emulsion-Special-Shade-630x630-removebg-preview.png', 1450, 4950, 23000, true),
('Diamond Overall Weather Max', 'Diamond', 'decorative', 'exterior', 'Maximum weather shield protection', '/images/products/diamond/pverall weather max.webp', 1850, 6350, 29500, true),
('Diamond Red Oxide Wood & Metal', 'Diamond', 'decorative', 'wood_metal', 'Anti-corrosive red oxide primer', '/images/products/diamond/Red-Oxide-wood-and-metal-630x630-removebg-preview.png', 980, 3350, 15500, true),
('Diamond Roof Coat', 'Diamond', 'decorative', 'waterproofing', 'Protective coating for roof surfaces', '/images/products/diamond/roof coat.webp', 3200, 11000, 52000, true),
('Diamond Varnish', 'Diamond', 'decorative', 'wood_metal', 'Durable high gloss varnish', '/images/products/diamond/Warnish-630x630.png', 1900, 6500, 0, true),
('Diamond Water Matt', 'Diamond', 'decorative', 'wood_metal', 'Water based matt wood finish', '/images/products/diamond/Water-Matt-1-1024x657-removebg-preview.png', 1550, 5300, 0, true),
('Diamond Weather Protector', 'Diamond', 'decorative', 'exterior', 'All-weather exterior protector', '/images/products/diamond/weather protector.png', 1700, 5800, 27000, true),
('Diamond Ace Multi Finish', 'Diamond', 'decorative', 'interior', 'Versatile multi-surface wall finish', '/images/products/diamond/WhatsApp-Image-2024-11-18-at-15.08.00-1024x656-removebg-preview.png', 1500, 5100, 23500, true),
('Diamond Premium Wall Coating', 'Diamond', 'decorative', 'interior', 'High fidelity interior wall paint', '/images/products/diamond/WhatsApp_Image_2026-02-21_at_1.14.18_AM-removebg-preview.png', 1650, 5650, 26500, true);

-- ------------------------------------------------------------------------------------------------
-- RELIANCE PRODUCTS (8)
-- ------------------------------------------------------------------------------------------------
INSERT INTO products (name, brand, category, sub_category, description, image_url, price_quarter, price_gallon, price_drum, in_stock) VALUES
('Reliance Acrylic Putty', 'Reliance', 'decorative', 'accessories', 'Smooth acrylic wall putty', '/images/products/reliance/Reliance-Acrylic-Putty.png', 650, 2200, 0, true),
('Reliance Matt Enamel', 'Reliance', 'decorative', 'wood_metal', 'Non-reflective matt enamel finish', '/images/products/reliance/Reliance-Matt-Enamel.png', 1650, 5600, 26000, true),
('Reliance Red Oxide Primer', 'Reliance', 'decorative', 'wood_metal', 'Corrosion resistant red oxide', '/images/products/reliance/Reliance-Red-Oxide-Primer.png', 920, 3150, 0, true),
('Reliance Semi Plastic Emulsion', 'Reliance', 'decorative', 'interior', 'Semi plastic wall emulsion', '/images/products/reliance/Reliance-Semi-Plastic-Emulsion.png', 1180, 4000, 18500, true),
('Reliance Stainless Matt', 'Reliance', 'decorative', 'wood_metal', 'Premium stainless matt finish', '/images/products/reliance/Reliance-Stainless-Matt.png', 1800, 6100, 28000, true),
('Reliance Wall Primer Sealer', 'Reliance', 'decorative', 'accessories', 'Multi-purpose wall primer sealer', '/images/products/reliance/Reliance-Wall-Primer-Sealer.png', 580, 1950, 9200, true),
('Reliance Water Primer Sealer', 'Reliance', 'decorative', 'accessories', 'Sealer for water based paints', '/images/products/reliance/Reliance-Water-Primer-Sealer.png', 540, 1850, 8800, true),
('Reliance Weather Guard', 'Reliance', 'decorative', 'exterior', 'Exterior grade weather guard coating', '/images/products/reliance/Reliance-Weather-Guard.png', 1550, 5300, 24500, true);

-- ------------------------------------------------------------------------------------------------
-- RELIABLE PRODUCTS (11)
-- ------------------------------------------------------------------------------------------------
INSERT INTO products (name, brand, category, sub_category, description, image_url, price_quarter, price_gallon, price_drum, in_stock) VALUES
('Reliable Ace Flexi Primer', 'Reliable', 'decorative', 'accessories', 'High flexibility wall primer', '/images/products/reliable/AceFlexiprimer_68b92dcf-b2dc-4299-8666-44c8af138854.webp', 740, 2500, 11000, true),
('Reliable Everlast Weather Proof', 'Reliable', 'decorative', 'exterior', 'Maximum durability weather protection', '/images/products/reliable/Everlast-Weather-Proof.webp', 1850, 6300, 29000, true),
('Reliable Ace Durasilk Emulsion', 'Reliable', 'decorative', 'interior', 'Smooth interior Durasilk finish', '/images/products/reliable/ace Durasilk emulsion.webp', 1550, 5300, 24500, true),
('Reliable Ace Gloss Lacquer', 'Reliable', 'decorative', 'wood_metal', 'Mirror finish wood lacquer', '/images/products/reliable/ace Gloss-lacquer-Timberlac_acfb771b-f4b1-40cc-aa0b-1f42246bc090.webp', 2400, 8200, 0, true),
('Reliable Ace Hi Sparkle Metallic', 'Reliable', 'decorative', 'interior', 'Intense sparkle metallic finish', '/images/products/reliable/ace Hi sparkle metalic_087a2ef0-925d-43a8-9d04-c36e344d4990.webp', 1900, 6500, 0, true),
('Reliable Ace Matt Enamel', 'Reliable', 'decorative', 'wood_metal', 'Elite series matt enamel', '/images/products/reliable/ace matt enamel.webp', 1750, 6000, 28000, true),
('Reliable Ace Super Gloss Enamel', 'Reliable', 'decorative', 'wood_metal', 'Ultra-high gloss gloss enamel', '/images/products/reliable/ace super gloss enamel.webp', 1950, 6700, 31000, true),
('Reliable Ace Weather Defender', 'Reliable', 'decorative', 'exterior', 'Top tier exterior defender', '/images/products/reliable/ace weather defender.webp', 1800, 6150, 28500, true),
('Reliable Ace Water Based Primer', 'Reliable', 'decorative', 'accessories', 'Quality base primer for walls', '/images/products/reliable/ace water-based-primer.webp', 620, 2150, 10000, true),
('Reliable Everlast High Gloss Enamel', 'Reliable', 'decorative', 'wood_metal', 'Long-lasting high gloss enamel', '/images/products/reliable/everlast high gloss enamel.webp', 1900, 6500, 30000, true),
('Reliable Overall Super Emulsion', 'Reliable', 'decorative', 'interior', 'Professional grade super emulsion', '/images/products/reliable/overall super emulsion.webp', 1450, 4950, 23000, true);
