import { Shade } from '@/types';

export const BRIGHTO_SHADES: Shade[] = [
  { id: '9000', product_id: '', name: 'Brilliant White', code: '9000', hex: '#FFFFFF', is_drum_available: true },
  { id: '9012', product_id: '', name: 'Off White', code: '9012', hex: '#FAF9F6', is_drum_available: true },
  { id: '9041', product_id: '', name: 'Ash White', code: '9041', hex: '#F2F2F2', is_drum_available: true },
  { id: '9071', product_id: '', name: 'Lavender White', code: '9071', hex: '#F4F0FF', is_drum_available: false },
  { id: '9805', product_id: '', name: 'Wisteria White', code: '9805', hex: '#FDF5E6', is_drum_available: false },
  { id: '9807', product_id: '', name: 'Twilight', code: '9807', hex: '#E6E6FA', is_drum_available: false },
  { id: '9802', product_id: '', name: 'Kitten White', code: '9802', hex: '#FFF5EE', is_drum_available: false },
  { id: '9141', product_id: '', name: 'New Ash White', code: '9141', hex: '#E8E8E8', is_drum_available: false },
  { id: '9808', product_id: '', name: 'Silver Grey', code: '9808', hex: '#C0C0C0', is_drum_available: false },
  { id: '9809', product_id: '', name: 'Shell Grey', code: '9809', hex: '#D3D3D3', is_drum_available: false },
  { id: '9803', product_id: '', name: 'Dove White', code: '9803', hex: '#F8F8F8', is_drum_available: false },
  { id: '9684', product_id: '', name: 'Goose Wing', code: '9684', hex: '#DCDCDC', is_drum_available: false },
  { id: '9681', product_id: '', name: 'Ice Grey', code: '9681', hex: '#D1D1D1', is_drum_available: false },
  { id: '9070', product_id: '', name: 'Rose White', code: '9070', hex: '#FFF0F5', is_drum_available: false },
  { id: '9043', product_id: '', name: 'Whisper', code: '9043', hex: '#F5F5F5', is_drum_available: false },
  { id: '9046', product_id: '', name: 'Dove Grey', code: '9046', hex: '#A9A9A9', is_drum_available: false },
  { id: '9001', product_id: '', name: 'Cream', code: '9001', hex: '#FFFDD0', is_drum_available: false },
  { id: '9801', product_id: '', name: 'Ivory Silk', code: '9801', hex: '#FFFFF0', is_drum_available: false },
  { id: '9040', product_id: '', name: 'Peach Cream', code: '9040', hex: '#FFEFD5', is_drum_available: false },
  { id: '9306', product_id: '', name: 'Champaign', code: '9306', hex: '#F7E7CE', is_drum_available: false },
  { id: '9048', product_id: '', name: 'Badami', code: '9048', hex: '#EEDC82', is_drum_available: false },
  { id: '9804', product_id: '', name: 'Brazil Nut', code: '9804', hex: '#A67B5B', is_drum_available: false },
  { id: '9042', product_id: '', name: 'Sand Stone', code: '9042', hex: '#C2B280', is_drum_available: false },
  { id: '9017', product_id: '', name: 'Stone', code: '9017', hex: '#8B8680', is_drum_available: false },
  { id: '9305', product_id: '', name: 'Coca Milk', code: '9305', hex: '#D2B48C', is_drum_available: false },
  { id: '9022', product_id: '', name: 'Chocolate', code: '9022', hex: '#7B3F00', is_drum_available: false },
  { id: '9045', product_id: '', name: 'Pale Peach', code: '9045', hex: '#FFDAB9', is_drum_available: false },
  { id: '9050', product_id: '', name: 'Rose Petal', code: '9050', hex: '#F7CAC9', is_drum_available: false },
  { id: '9302', product_id: '', name: 'Palm Peach Pink', code: '9302', hex: '#FFD1DC', is_drum_available: false },
  { id: '9024', product_id: '', name: 'Apricot', code: '9024', hex: '#FBCEB1', is_drum_available: false },
  { id: '9686', product_id: '', name: 'Tea Rose', code: '9686', hex: '#F4C2C2', is_drum_available: false },
  { id: '9221', product_id: '', name: 'Deep Pink', code: '9221', hex: '#FF1493', is_drum_available: false },
  { id: '9688', product_id: '', name: 'Coral Spice', code: '9688', hex: '#E2725B', is_drum_available: false },
  { id: '9015', product_id: '', name: 'Rose Pink', code: '9015', hex: '#FF66CC', is_drum_available: false },
  { id: '9009', product_id: '', name: 'Brighto Pink', code: '9009', hex: '#FF007F', is_drum_available: false },
  { id: '9300', product_id: '', name: 'Summer Pink', code: '9300', hex: '#FFB6C1', is_drum_available: false },
  { id: '9222', product_id: '', name: 'Carnival Pink', code: '9222', hex: '#E4007C', is_drum_available: false },
  { id: '9007', product_id: '', name: 'Brighto Red', code: '9007', hex: '#ED1C24', is_drum_available: false },
  { id: '9690', product_id: '', name: 'Pastle Green', code: '9690', hex: '#77DD77', is_drum_available: false },
  { id: '9506', product_id: '', name: 'Fresh Green', code: '9506', hex: '#90EE90', is_drum_available: false },
  { id: '9689', product_id: '', name: 'Pine Frost', code: '9689', hex: '#E0F2F1', is_drum_available: false },
  { id: '9006', product_id: '', name: 'Lime Green', code: '9006', hex: '#32CD32', is_drum_available: false },
  { id: '9010', product_id: '', name: 'Melody Green', code: '9010', hex: '#98FF98', is_drum_available: false },
  { id: '9027', product_id: '', name: 'Apple Green', code: '9027', hex: '#8DB600', is_drum_available: false },
  { id: '9004', product_id: '', name: 'Brighto Green', code: '9004', hex: '#008000', is_drum_available: false },
  { id: '9510', product_id: '', name: 'Forest Green', code: '9510', hex: '#228B22', is_drum_available: false },
  { id: '9513', product_id: '', name: 'Green Summit', code: '9513', hex: '#004225', is_drum_available: false },
  { id: '9035', product_id: '', name: 'Leaf Green', code: '9035', hex: '#3CB371', is_drum_available: false },
  { id: '9011', product_id: '', name: 'Lilac', code: '9011', hex: '#C8A2C8', is_drum_available: false },
  { id: '9683', product_id: '', name: 'Soothing Lilac', code: '9683', hex: '#E6E6FA', is_drum_available: false },
  { id: '9501', product_id: '', name: 'Purple', code: '9501', hex: '#800080', is_drum_available: false },
  { id: '9014', product_id: '', name: 'Ice Blue', code: '9014', hex: '#AFEEEE', is_drum_available: false },
  { id: '9002', product_id: '', name: 'Light Blue', code: '9002', hex: '#ADD8E6', is_drum_available: false },
  { id: '9008', product_id: '', name: 'Brighto Blue', code: '9008', hex: '#0000FF', is_drum_available: false },
  { id: '9502', product_id: '', name: 'Peacock Plum', code: '9502', hex: '#BDB76B', is_drum_available: false },
  { id: '9503', product_id: '', name: 'Fluorite', code: '9503', hex: '#996515', is_drum_available: false },
  { id: '9508', product_id: '', name: 'Electric Blue', code: '9508', hex: '#7DF9FF', is_drum_available: false },
  { id: '9072', product_id: '', name: 'Cockleshell', code: '9072', hex: '#FFE5B4', is_drum_available: false },
  { id: '9303', product_id: '', name: 'Zephyr', code: '9303', hex: '#778899', is_drum_available: false },
  { id: '9687', product_id: '', name: 'Cameo', code: '9687', hex: '#D2B48C', is_drum_available: false },
  { id: '9692', product_id: '', name: 'Parasol', code: '9692', hex: '#EEDC82', is_drum_available: false },
  { id: '9332', product_id: '', name: 'Classical', code: '9332', hex: '#F5F5DC', is_drum_available: false },
  { id: '9005', product_id: '', name: 'Orange', code: '9005', hex: '#FFA500', is_drum_available: false },
  { id: '9698', product_id: '', name: 'Terracotta', code: '9698', hex: '#E2725B', is_drum_available: false },
  { id: '9810', product_id: '', name: 'Black', code: '9810', hex: '#000000', is_drum_available: false }
];

// Brighto Synthetic Enamel shades (extracted from official 2025 shade card PDF)
export const BRIGHTO_ENAMEL_SHADES: Shade[] = [
  // Whites & Creams
  { id: 'e3000', product_id: '', name: 'Brilliant White', code: '3000', hex: '#FFFFFF', is_drum_available: true },
  { id: 'e3101', product_id: '', name: 'Off White', code: '3101', hex: '#FAF0E6', is_drum_available: true },
  { id: 'e3051', product_id: '', name: 'Bone White', code: '3051', hex: '#F9F6EE', is_drum_available: false },
  { id: 'e3001', product_id: '', name: 'Cream', code: '3001', hex: '#FFFDD0', is_drum_available: false },
  { id: 'e3071', product_id: '', name: 'Pale Cream', code: '3071', hex: '#FFF8DC', is_drum_available: false },
  { id: 'e3410', product_id: '', name: 'Antique White', code: '3410', hex: '#FAEBD7', is_drum_available: false },
  { id: 'e3042', product_id: '', name: 'Ash White', code: '3042', hex: '#E8E8E8', is_drum_available: false },
  { id: 'e3411', product_id: '', name: 'Antique Ash', code: '3411', hex: '#D5D5D0', is_drum_available: false },
  // Beiges & Browns
  { id: 'e3078', product_id: '', name: 'Diyar', code: '3078', hex: '#C19A6B', is_drum_available: false },
  { id: 'e3050', product_id: '', name: 'Beige', code: '3050', hex: '#F5F5DC', is_drum_available: false },
  { id: 'e3086', product_id: '', name: 'Yellow Oxide', code: '3086', hex: '#E49B0F', is_drum_available: false },
  { id: 'e3088', product_id: '', name: 'Caterpillar', code: '3088', hex: '#FFC300', is_drum_available: false },
  { id: 'e3055', product_id: '', name: 'Clay', code: '3055', hex: '#B66A50', is_drum_available: false },
  { id: 'e3077', product_id: '', name: 'Champagne', code: '3077', hex: '#F7E7CE', is_drum_available: false },
  { id: 'e3029', product_id: '', name: 'Ochre', code: '3029', hex: '#CC7722', is_drum_available: false },
  { id: 'e3403', product_id: '', name: 'Teak', code: '3403', hex: '#B08A53', is_drum_available: false },
  { id: 'e3404', product_id: '', name: 'Sheesham', code: '3404', hex: '#8B6914', is_drum_available: false },
  { id: 'e3031', product_id: '', name: 'Brighto Brown', code: '3031', hex: '#654321', is_drum_available: false },
  { id: 'e3074', product_id: '', name: 'Golden Brown', code: '3074', hex: '#996515', is_drum_available: false },
  { id: 'e3075', product_id: '', name: 'Dark Brown', code: '3075', hex: '#5C4033', is_drum_available: false },
  { id: 'e3402', product_id: '', name: 'Brown', code: '3402', hex: '#8B4513', is_drum_available: false },
  { id: 'e3084', product_id: '', name: 'Antelope', code: '3084', hex: '#A38459', is_drum_available: false },
  { id: 'e3030', product_id: '', name: 'Coriander', code: '3030', hex: '#8B8B00', is_drum_available: false },
  // Greys
  { id: 'e3004', product_id: '', name: 'Dark Grey', code: '3004', hex: '#555555', is_drum_available: false },
  { id: 'e3019', product_id: '', name: 'Scarab', code: '3019', hex: '#3B3C36', is_drum_available: false },
  { id: 'e3409', product_id: '', name: 'Antique Grey', code: '3409', hex: '#8A8A7A', is_drum_available: false },
  { id: 'e3072', product_id: '', name: 'Oyster', code: '3072', hex: '#DED3C4', is_drum_available: false },
  { id: 'e3080', product_id: '', name: 'Court Grey', code: '3080', hex: '#9B9B9B', is_drum_available: false },
  { id: 'e3087', product_id: '', name: 'Sleek Grey', code: '3087', hex: '#708090', is_drum_available: false },
  { id: 'e3005', product_id: '', name: 'Brighto Grey', code: '3005', hex: '#808080', is_drum_available: false },
  { id: 'e3003', product_id: '', name: 'Light Grey', code: '3003', hex: '#D3D3D3', is_drum_available: false },
  { id: 'e3105', product_id: '', name: 'Smoke Grey', code: '3105', hex: '#738678', is_drum_available: false },
  // Greens
  { id: 'e3085', product_id: '', name: 'Deep Ocean', code: '3085', hex: '#003B46', is_drum_available: false },
  { id: 'e3073', product_id: '', name: 'Eau-De-Nil', code: '3073', hex: '#99C5C4', is_drum_available: false },
  { id: 'e3028', product_id: '', name: 'Spring Green', code: '3028', hex: '#00FF7F', is_drum_available: false },
  { id: 'e3022', product_id: '', name: 'Emerald', code: '3022', hex: '#50C878', is_drum_available: false },
  { id: 'e3023', product_id: '', name: 'Adams Green', code: '3023', hex: '#355E3B', is_drum_available: false },
  { id: 'e3027', product_id: '', name: 'Sea Green', code: '3027', hex: '#2E8B57', is_drum_available: false },
  { id: 'e3041', product_id: '', name: 'Royal Green', code: '3041', hex: '#136207', is_drum_available: false },
  // Blues
  { id: 'e3018', product_id: '', name: 'Royal Blue', code: '3018', hex: '#4169E1', is_drum_available: false },
  { id: 'e3070', product_id: '', name: 'Comet Blue', code: '3070', hex: '#5F6BBE', is_drum_available: false },
  { id: 'e3034', product_id: '', name: 'H.R. Blue', code: '3034', hex: '#003399', is_drum_available: false },
  { id: 'e3032', product_id: '', name: 'Deep Blue', code: '3032', hex: '#00008B', is_drum_available: false },
  { id: 'e3016', product_id: '', name: 'Light Blue', code: '3016', hex: '#ADD8E6', is_drum_available: false },
  { id: 'e3035', product_id: '', name: 'Vivid Blue', code: '3035', hex: '#1E90FF', is_drum_available: false },
  { id: 'e3017', product_id: '', name: 'Brighto Blue', code: '3017', hex: '#0000FF', is_drum_available: false },
  // Purples
  { id: 'e3033', product_id: '', name: 'Violet', code: '3033', hex: '#8B00FF', is_drum_available: false },
  { id: 'e3401', product_id: '', name: 'Mauve', code: '3401', hex: '#E0B0FF', is_drum_available: false },
  { id: 'e3076', product_id: '', name: 'Pumice', code: '3076', hex: '#B5B5A5', is_drum_available: false },
  // Reds & Pinks
  { id: 'e3011', product_id: '', name: 'Red Oxide', code: '3011', hex: '#6D1008', is_drum_available: false },
  { id: 'e3008', product_id: '', name: 'Signal Red', code: '3008', hex: '#FF0000', is_drum_available: false },
  { id: 'e3009', product_id: '', name: 'P. O. Red', code: '3009', hex: '#BF0A30', is_drum_available: false },
  { id: 'e3012', product_id: '', name: 'Crimson', code: '3012', hex: '#DC143C', is_drum_available: false },
  { id: 'e3115', product_id: '', name: 'Baby Pink', code: '3115', hex: '#F4C2C2', is_drum_available: false },
  { id: 'e3114', product_id: '', name: 'Peach Shadow', code: '3114', hex: '#FFDAB9', is_drum_available: false },
  { id: 'e3052', product_id: '', name: 'Pink', code: '3052', hex: '#FFC0CB', is_drum_available: false },
  { id: 'e3020', product_id: '', name: 'Red Rose', code: '3020', hex: '#C21E56', is_drum_available: false },
  // Yellows & Oranges
  { id: 'e3006', product_id: '', name: 'Lemon', code: '3006', hex: '#FFF44F', is_drum_available: false },
  { id: 'e3002', product_id: '', name: 'Orange', code: '3002', hex: '#FF8C00', is_drum_available: false },
  { id: 'e3007', product_id: '', name: 'Golden Yellow', code: '3007', hex: '#FFD700', is_drum_available: false },
  { id: 'e3089', product_id: '', name: 'Elegant Orange', code: '3089', hex: '#FF7518', is_drum_available: false },
  // Black
  { id: 'e3102', product_id: '', name: 'Black', code: '3102', hex: '#000000', is_drum_available: false },
];

// Brighto Plastic Emulsion shades (extracted from official 2025 shade card PDF)
export const BRIGHTO_PLASTIC_EMULSION_SHADES: Shade[] = [
  // Whites
  { id: 'p6000', product_id: '', name: 'Brilliant White', code: '6000', hex: '#FFFFFF', is_drum_available: true },
  { id: 'p6212', product_id: '', name: 'Off White', code: '6212', hex: '#FAF0E6', is_drum_available: true },
  { id: 'p6100', product_id: '', name: 'Ash White', code: '6100', hex: '#E8E8E8', is_drum_available: true },
  { id: 'p6802', product_id: '', name: 'Swiss White', code: '6802', hex: '#FEFEFA', is_drum_available: false },
  { id: 'p6300', product_id: '', name: 'Lilly White', code: '6300', hex: '#FDF8F0', is_drum_available: false },
  { id: 'p6801', product_id: '', name: 'Kitten White', code: '6801', hex: '#FFF5EE', is_drum_available: false },
  { id: 'p6258', product_id: '', name: 'Dove White', code: '6258', hex: '#F8F8F8', is_drum_available: false },
  { id: 'p6400', product_id: '', name: 'Rose White', code: '6400', hex: '#FFF0F5', is_drum_available: false },
  { id: 'p6900', product_id: '', name: 'Lavender White', code: '6900', hex: '#F4F0FF', is_drum_available: false },
  { id: 'p6804', product_id: '', name: 'Whisper White', code: '6804', hex: '#F5F5F5', is_drum_available: false },
  { id: 'p6500', product_id: '', name: 'Apple White', code: '6500', hex: '#F0FFF0', is_drum_available: false },
  { id: 'p6704', product_id: '', name: 'Reflection White', code: '6704', hex: '#F0EDE8', is_drum_available: false },
  { id: 'p6707', product_id: '', name: 'New Ash White', code: '6707', hex: '#DFDFDF', is_drum_available: false },
  { id: 'p6903', product_id: '', name: 'Apricot White', code: '6903', hex: '#FFECD0', is_drum_available: false },
  // Creams & Beiges
  { id: 'p6201', product_id: '', name: 'Cream', code: '6201', hex: '#FFFDD0', is_drum_available: false },
  { id: 'p6501', product_id: '', name: 'Almond Wisp', code: '6501', hex: '#EFDECD', is_drum_available: false },
  { id: 'p6823', product_id: '', name: 'Peach Cream', code: '6823', hex: '#FFEFD5', is_drum_available: false },
  { id: 'p6502', product_id: '', name: 'Ivory Silk', code: '6502', hex: '#FFFFF0', is_drum_available: false },
  { id: 'p6626', product_id: '', name: 'Royal Beige', code: '6626', hex: '#D4B896', is_drum_available: false },
  { id: 'p6506', product_id: '', name: 'Manila Tan', code: '6506', hex: '#D2B48C', is_drum_available: false },
  { id: 'p6507', product_id: '', name: 'Brazil Nut', code: '6507', hex: '#A67B5B', is_drum_available: false },
  { id: 'p6504', product_id: '', name: 'Classical', code: '6504', hex: '#F5F5DC', is_drum_available: false },
  { id: 'p6907', product_id: '', name: 'Cockleshell', code: '6907', hex: '#FFE5B4', is_drum_available: false },
  { id: 'p6706', product_id: '', name: 'New Cockleshell', code: '6706', hex: '#F5DEB3', is_drum_available: false },
  { id: 'p6824', product_id: '', name: 'Parasol', code: '6824', hex: '#EEDC82', is_drum_available: false },
  { id: 'p6222', product_id: '', name: 'Chocolate', code: '6222', hex: '#7B3F00', is_drum_available: false },
  // Greys
  { id: 'p6708', product_id: '', name: 'Antique Grey', code: '6708', hex: '#8A8A7A', is_drum_available: false },
  // Pinks & Reds
  { id: 'p6173', product_id: '', name: 'Pink Violet', code: '6173', hex: '#CC8899', is_drum_available: false },
  { id: 'p6702', product_id: '', name: 'Coral Spice', code: '6702', hex: '#E2725B', is_drum_available: false },
  { id: 'p6508', product_id: '', name: 'Rose Water', code: '6508', hex: '#F7CAC9', is_drum_available: false },
  { id: 'p6260', product_id: '', name: 'Peach Goodness', code: '6260', hex: '#FFDAB9', is_drum_available: false },
  { id: 'p6252', product_id: '', name: 'Ice Red', code: '6252', hex: '#FFB3B3', is_drum_available: false },
  { id: 'p6813', product_id: '', name: 'Carnival Pink', code: '6813', hex: '#E4007C', is_drum_available: false },
  { id: 'p6209', product_id: '', name: 'Brighto Pink', code: '6209', hex: '#FF007F', is_drum_available: false },
  { id: 'p6822', product_id: '', name: 'Summer Pink', code: '6822', hex: '#FFB6C1', is_drum_available: false },
  { id: 'p6703', product_id: '', name: 'Deep Pink', code: '6703', hex: '#FF1493', is_drum_available: false },
  { id: 'p6251', product_id: '', name: 'Salmon', code: '6251', hex: '#FA8072', is_drum_available: false },
  { id: 'p6701', product_id: '', name: 'Cold Candy', code: '6701', hex: '#FFD1DC', is_drum_available: false },
  { id: 'p6207', product_id: '', name: 'Brighto Red', code: '6207', hex: '#ED1C24', is_drum_available: false },
  { id: 'p6171', product_id: '', name: 'Salsa', code: '6171', hex: '#CC3333', is_drum_available: false },
  { id: 'p6505', product_id: '', name: 'Red Fog', code: '6505', hex: '#CC4444', is_drum_available: false },
  // Oranges & Yellows
  { id: 'p6250', product_id: '', name: 'Stunning Gold', code: '6250', hex: '#DAA520', is_drum_available: false },
  { id: 'p6816', product_id: '', name: 'Gold Mist', code: '6816', hex: '#D4AF37', is_drum_available: false },
  { id: 'p6811', product_id: '', name: 'African Orange', code: '6811', hex: '#FF6600', is_drum_available: false },
  { id: 'p6818', product_id: '', name: 'Rust Dust', code: '6818', hex: '#B7410E', is_drum_available: false },
  { id: 'p6253', product_id: '', name: 'Arizona Sunset', code: '6253', hex: '#FF6347', is_drum_available: false },
  { id: 'p6444', product_id: '', name: 'Coral Reef', code: '6444', hex: '#FF7F50', is_drum_available: false },
  { id: 'p6555', product_id: '', name: 'Mango Yellow', code: '6555', hex: '#FFD700', is_drum_available: false },
  { id: 'p6814', product_id: '', name: 'Lemon Yellow', code: '6814', hex: '#FFF44F', is_drum_available: false },
  { id: 'p6805', product_id: '', name: 'Sunburst', code: '6805', hex: '#FFCF48', is_drum_available: false },
  // Greens
  { id: 'p6236', product_id: '', name: 'Apple Green', code: '6236', hex: '#8DB600', is_drum_available: false },
  { id: 'p6809', product_id: '', name: 'Forest Green', code: '6809', hex: '#228B22', is_drum_available: false },
  { id: 'p6810', product_id: '', name: 'Green Stone', code: '6810', hex: '#4A766E', is_drum_available: false },
  { id: 'p6205', product_id: '', name: 'Lime Juice', code: '6205', hex: '#CCFF00', is_drum_available: false },
  { id: 'p6705', product_id: '', name: 'Jade', code: '6705', hex: '#00A86B', is_drum_available: false },
  // Blues
  { id: 'p6777', product_id: '', name: 'Eveline Blue', code: '6777', hex: '#5B9BD5', is_drum_available: false },
  { id: 'p6819', product_id: '', name: 'Brighto Blue', code: '6819', hex: '#0000FF', is_drum_available: false },
  { id: 'p6820', product_id: '', name: 'Indigo', code: '6820', hex: '#4B0082', is_drum_available: false },
  { id: 'p6254', product_id: '', name: 'Celestial', code: '6254', hex: '#4997D0', is_drum_available: false },
  { id: 'p6259', product_id: '', name: 'Ice Star', code: '6259', hex: '#B0E0E6', is_drum_available: false },
  { id: 'p6257', product_id: '', name: 'Ice Age', code: '6257', hex: '#D6EBFF', is_drum_available: false },
  // Other
  { id: 'p6806', product_id: '', name: 'Walkabout', code: '6806', hex: '#C19A6B', is_drum_available: false },
  { id: 'p6905', product_id: '', name: 'Sherbet', code: '6905', hex: '#F5E6CB', is_drum_available: false },
  // Black
  { id: 'p6821', product_id: '', name: 'Black', code: '6821', hex: '#000000', is_drum_available: false },
];

// Brighto All Weather shades (extracted from official 2025 shade card PDF)
export const BRIGHTO_ALL_WEATHER_SHADES: Shade[] = [
  // Whites & Creams
  { id: 'w7000', product_id: '', name: 'Brilliant White', code: '7000', hex: '#FFFFFF', is_drum_available: true },
  { id: 'w7121', product_id: '', name: 'Off White', code: '7121', hex: '#FAF0E6', is_drum_available: true },
  { id: 'w7424', product_id: '', name: 'Ash White', code: '7424', hex: '#E8E8E8', is_drum_available: false },
  { id: 'w7373', product_id: '', name: 'Lemon White', code: '7373', hex: '#FFFDE7', is_drum_available: false },
  { id: 'w7240', product_id: '', name: 'Ivory', code: '7240', hex: '#FFFFF0', is_drum_available: false },
  { id: 'w7125', product_id: '', name: 'Magnolia', code: '7125', hex: '#F8F4FF', is_drum_available: false },
  // Beiges & Tans
  { id: 'w7626', product_id: '', name: 'Beige', code: '7626', hex: '#F5F5DC', is_drum_available: false },
  { id: 'w7207', product_id: '', name: 'Honey Milk', code: '7207', hex: '#FFEFD5', is_drum_available: false },
  { id: 'w7122', product_id: '', name: 'Sugar Cane', code: '7122', hex: '#F5F0E1', is_drum_available: false },
  { id: 'w7120', product_id: '', name: 'Silk Stone', code: '7120', hex: '#E8DCC8', is_drum_available: false },
  { id: 'w7103', product_id: '', name: 'Almond', code: '7103', hex: '#EFDECD', is_drum_available: false },
  { id: 'w7127', product_id: '', name: 'Cameo', code: '7127', hex: '#D2B48C', is_drum_available: false },
  { id: 'w7128', product_id: '', name: 'Hopsack', code: '7128', hex: '#C4A882', is_drum_available: false },
  { id: 'w7105', product_id: '', name: 'Dusty Stone', code: '7105', hex: '#B8A590', is_drum_available: false },
  { id: 'w7525', product_id: '', name: 'Sand Stone', code: '7525', hex: '#C2B280', is_drum_available: false },
  { id: 'w7601', product_id: '', name: 'Cockleshell', code: '7601', hex: '#FFE5B4', is_drum_available: false },
  { id: 'w7123', product_id: '', name: 'Autumn Stone', code: '7123', hex: '#BFA585', is_drum_available: false },
  { id: 'w7201', product_id: '', name: 'Camel Coat', code: '7201', hex: '#C19A6B', is_drum_available: false },
  { id: 'w7426', product_id: '', name: 'Cinnamon', code: '7426', hex: '#D2691E', is_drum_available: false },
  { id: 'w7107', product_id: '', name: 'Golden Needles', code: '7107', hex: '#DAA520', is_drum_available: false },
  // Browns
  { id: 'w7820', product_id: '', name: 'Moorland', code: '7820', hex: '#8B6914', is_drum_available: false },
  { id: 'w7205', product_id: '', name: 'Molten Bronze', code: '7205', hex: '#8C5B3E', is_drum_available: false },
  { id: 'w7009', product_id: '', name: 'Beaver', code: '7009', hex: '#9F8170', is_drum_available: false },
  // Greys
  { id: 'w7200', product_id: '', name: 'Stone Grey', code: '7200', hex: '#928E85', is_drum_available: false },
  { id: 'w7727', product_id: '', name: 'Silver Mist', code: '7727', hex: '#C0C0C0', is_drum_available: false },
  { id: 'w7602', product_id: '', name: 'Smokey Wings', code: '7602', hex: '#8A8682', is_drum_available: false },
  { id: 'w7826', product_id: '', name: 'Port Land', code: '7826', hex: '#A9A29E', is_drum_available: false },
  { id: 'w7603', product_id: '', name: 'Antique Grey', code: '7603', hex: '#8A8A7A', is_drum_available: false },
  { id: 'w7829', product_id: '', name: 'Sky Grey', code: '7829', hex: '#B8C4CC', is_drum_available: false },
  { id: 'w7102', product_id: '', name: 'Wirework Grey', code: '7102', hex: '#7D7D7D', is_drum_available: false },
  { id: 'w7017', product_id: '', name: 'Charcoal', code: '7017', hex: '#36454F', is_drum_available: false },
  // Peach & Pink
  { id: 'w7108', product_id: '', name: 'Sweet Peach', code: '7108', hex: '#FFDAB9', is_drum_available: false },
  { id: 'w7526', product_id: '', name: 'Tea Rose', code: '7526', hex: '#F4C2C2', is_drum_available: false },
  { id: 'w7506', product_id: '', name: 'Peach', code: '7506', hex: '#FFE5B4', is_drum_available: false },
  { id: 'w7203', product_id: '', name: 'Porcelain Peach', code: '7203', hex: '#FFECD0', is_drum_available: false },
  { id: 'w7374', product_id: '', name: 'Evening Blush', code: '7374', hex: '#F2C9CC', is_drum_available: false },
  { id: 'w7111', product_id: '', name: 'Sweet Jewel', code: '7111', hex: '#E8A0B8', is_drum_available: false },
  { id: 'w7249', product_id: '', name: 'Brighto Pink', code: '7249', hex: '#FF007F', is_drum_available: false },
  // Reds & Oranges
  { id: 'w7326', product_id: '', name: 'Rex Yellow', code: '7326', hex: '#FADA5E', is_drum_available: false },
  { id: 'w7246', product_id: '', name: 'Arizona Sunset', code: '7246', hex: '#FF6347', is_drum_available: false },
  { id: 'w7510', product_id: '', name: 'Red Rose', code: '7510', hex: '#C21E56', is_drum_available: false },
  { id: 'w7023', product_id: '', name: 'Terracotta', code: '7023', hex: '#E2725B', is_drum_available: false },
  { id: 'w7021', product_id: '', name: 'Red Oxide', code: '7021', hex: '#6D1008', is_drum_available: false },
  { id: 'w7020', product_id: '', name: 'Tile Red', code: '7020', hex: '#B5332E', is_drum_available: false },
  { id: 'w7022', product_id: '', name: 'Roof Tile', code: '7022', hex: '#A0522D', is_drum_available: false },
  { id: 'w7206', product_id: '', name: 'Desert Dawn', code: '7206', hex: '#EDC9AF', is_drum_available: false },
  { id: 'w7109', product_id: '', name: 'Moon Shade', code: '7109', hex: '#C5B9A8', is_drum_available: false },
  // Greens
  { id: 'w7255', product_id: '', name: 'Apple Green', code: '7255', hex: '#8DB600', is_drum_available: false },
  { id: 'w7929', product_id: '', name: 'Spring Green', code: '7929', hex: '#00FF7F', is_drum_available: false },
  { id: 'w7504', product_id: '', name: 'Forest Green', code: '7504', hex: '#228B22', is_drum_available: false },
  { id: 'w7202', product_id: '', name: 'Blue Green', code: '7202', hex: '#0D98BA', is_drum_available: false },
  // Blues & Purples
  { id: 'w7247', product_id: '', name: 'Electric Blue', code: '7247', hex: '#7DF9FF', is_drum_available: false },
  { id: 'w7204', product_id: '', name: 'Sea Wind', code: '7204', hex: '#87CEEB', is_drum_available: false },
  { id: 'w7503', product_id: '', name: 'Pacific Ocean', code: '7503', hex: '#1CA9C9', is_drum_available: false },
  { id: 'w7821', product_id: '', name: 'Admiral', code: '7821', hex: '#1B3B6F', is_drum_available: false },
  { id: 'w7253', product_id: '', name: 'Indigo', code: '7253', hex: '#4B0082', is_drum_available: false },
  { id: 'w7101', product_id: '', name: 'Lilac Dream', code: '7101', hex: '#C8A2C8', is_drum_available: false },
  { id: 'w7900', product_id: '', name: 'Brighto Mauve', code: '7900', hex: '#E0B0FF', is_drum_available: false },
  { id: 'w7375', product_id: '', name: 'Violet Bloom', code: '7375', hex: '#7F00FF', is_drum_available: false },
  // Black
  { id: 'w7314', product_id: '', name: 'Black', code: '7314', hex: '#000000', is_drum_available: false },
];

export const SAASI_HYDROUS_SHADES: Shade[] = [
  { id: 'saasi-hydrous-1', product_id: '', name: 'Off White', code: '6301', hex: '#F9F4E3', is_drum_available: false },
  { id: 'saasi-hydrous-2', product_id: '', name: 'Crisp', code: '6324', hex: '#F8F5DC', is_drum_available: false },
  { id: 'saasi-hydrous-3', product_id: '', name: 'Mobe Pearl', code: '6335', hex: '#EFDFCA', is_drum_available: false },
  { id: 'saasi-hydrous-4', product_id: '', name: 'Almond Sand', code: '6330', hex: '#E7D5B8', is_drum_available: false },
  { id: 'saasi-hydrous-5', product_id: '', name: 'Palace White', code: '6327', hex: '#F9EED1', is_drum_available: false },
  { id: 'saasi-hydrous-6', product_id: '', name: 'Candle Wax', code: '6331', hex: '#F1DEC0', is_drum_available: false },
  { id: 'saasi-hydrous-7', product_id: '', name: 'Evening Tea', code: '6305', hex: '#FAD0A1', is_drum_available: false },
  { id: 'saasi-hydrous-8', product_id: '', name: 'Sweet Cream', code: '6325', hex: '#F8D18C', is_drum_available: false },
  { id: 'saasi-hydrous-9', product_id: '', name: 'Flax Straw', code: '6336', hex: '#E2C995', is_drum_available: false },
  { id: 'saasi-hydrous-10', product_id: '', name: 'Apricot', code: '6306', hex: '#F4AF7A', is_drum_available: false },
  { id: 'saasi-hydrous-11', product_id: '', name: 'Natural Paprika', code: '6307', hex: '#CE7256', is_drum_available: false },
  { id: 'saasi-hydrous-12', product_id: '', name: 'Trondheim', code: '6332', hex: '#A6805D', is_drum_available: false },
  { id: 'saasi-hydrous-13', product_id: '', name: 'Lavender', code: '6362', hex: '#B4B9D6', is_drum_available: false },
  { id: 'saasi-hydrous-14', product_id: '', name: 'Angel Blue', code: '6340', hex: '#DAEFE6', is_drum_available: false },
  { id: 'saasi-hydrous-15', product_id: '', name: 'Peach Shadow', code: '6321', hex: '#F8D1B4', is_drum_available: false },
  { id: 'saasi-hydrous-16', product_id: '', name: 'Baby Pink', code: '6308', hex: '#F9D8D2', is_drum_available: false },
  { id: 'saasi-hydrous-17', product_id: '', name: 'Pink Orchard', code: '6349', hex: '#A66E99', is_drum_available: false },
  { id: 'saasi-hydrous-18', product_id: '', name: 'Purple Aster', code: '6312', hex: '#E0CFD8', is_drum_available: false },
  { id: 'saasi-hydrous-19', product_id: '', name: 'Soft Blue', code: '6315', hex: '#C4E4F2', is_drum_available: false },
  { id: 'saasi-hydrous-20', product_id: '', name: 'Red Buff', code: '6333', hex: '#B56D56', is_drum_available: false },
  { id: 'saasi-hydrous-21', product_id: '', name: 'Petal Pink', code: '6339', hex: '#E4CAC3', is_drum_available: false },
  { id: 'saasi-hydrous-22', product_id: '', name: 'Carnival Pink', code: '6313', hex: '#B368A6', is_drum_available: false },
  { id: 'saasi-hydrous-23', product_id: '', name: 'Purple', code: '6343', hex: '#6E5C8D', is_drum_available: false },
  { id: 'saasi-hydrous-24', product_id: '', name: 'Ice Turquoise', code: '6361', hex: '#85D4F5', is_drum_available: false },
  { id: 'saasi-hydrous-25', product_id: '', name: 'Fresh Pasta', code: '6322', hex: '#EAE3BA', is_drum_available: false },
  { id: 'saasi-hydrous-26', product_id: '', name: 'Angelica Pink', code: '6309', hex: '#F5C2CD', is_drum_available: false },
  { id: 'saasi-hydrous-27', product_id: '', name: 'Chilli Red', code: '6353', hex: '#853331', is_drum_available: false },
  { id: 'saasi-hydrous-28', product_id: '', name: 'Royal Orchard', code: '6345', hex: '#4C3C58', is_drum_available: false },
  { id: 'saasi-hydrous-29', product_id: '', name: 'Blue Flame', code: '6316', hex: '#3E6B9D', is_drum_available: false },
  { id: 'saasi-hydrous-30', product_id: '', name: 'Gold Rush', code: '6317', hex: '#A48D51', is_drum_available: false },
  { id: 'saasi-hydrous-31', product_id: '', name: 'Emily', code: '6311', hex: '#EEBFA9', is_drum_available: false },
  { id: 'saasi-hydrous-32', product_id: '', name: 'Adventure', code: '6314', hex: '#872E31', is_drum_available: false },
  { id: 'saasi-hydrous-33', product_id: '', name: 'Red Wine', code: '6350', hex: '#3C293C', is_drum_available: false },
  { id: 'saasi-hydrous-34', product_id: '', name: 'Navy Blue', code: '6354', hex: '#213C7A', is_drum_available: false },
  { id: 'saasi-hydrous-35', product_id: '', name: 'Ash White', code: '6318', hex: '#F8F4DF', is_drum_available: false },
  { id: 'saasi-hydrous-36', product_id: '', name: 'Ash Grey', code: '6357', hex: '#8A8E89', is_drum_available: false },
  { id: 'saasi-hydrous-37', product_id: '', name: 'Turquoise', code: '6347', hex: '#73C5B5', is_drum_available: false },
  { id: 'saasi-hydrous-38', product_id: '', name: 'Green Grape', code: '6320', hex: '#EFF4D2', is_drum_available: false },
  { id: 'saasi-hydrous-39', product_id: '', name: 'Vanilla Yellow', code: '6323', hex: '#FFF3C4', is_drum_available: false },
  { id: 'saasi-hydrous-40', product_id: '', name: 'Ego Shell', code: '6328', hex: '#EBE4D0', is_drum_available: false },
  { id: 'saasi-hydrous-41', product_id: '', name: 'Steel Grey', code: '6359', hex: '#778488', is_drum_available: false },
  { id: 'saasi-hydrous-42', product_id: '', name: 'Pacific Ocean', code: '6351', hex: '#3EAFAF', is_drum_available: false },
  { id: 'saasi-hydrous-43', product_id: '', name: 'Sherbet', code: '6342', hex: '#DAEED6', is_drum_available: false },
  { id: 'saasi-hydrous-44', product_id: '', name: 'Lemon Shine', code: '6326', hex: '#FCE07A', is_drum_available: false },
  { id: 'saasi-hydrous-45', product_id: '', name: 'Lavender White', code: '6319', hex: '#DED9D4', is_drum_available: false },
  { id: 'saasi-hydrous-46', product_id: '', name: 'Havana', code: '6360', hex: '#5C4530', is_drum_available: false },
  { id: 'saasi-hydrous-47', product_id: '', name: 'Ocean Dip', code: '6346', hex: '#3986A8', is_drum_available: false },
  { id: 'saasi-hydrous-48', product_id: '', name: 'Apple Green', code: '6310', hex: '#AFD38E', is_drum_available: false },
  { id: 'saasi-hydrous-49', product_id: '', name: 'Banana Yellow', code: '6329', hex: '#FFD555', is_drum_available: false },
  { id: 'saasi-hydrous-50', product_id: '', name: 'Snow White', code: '6356', hex: '#E4E0D6', is_drum_available: false },
  { id: 'saasi-hydrous-51', product_id: '', name: 'Dark Brown', code: '6337', hex: '#352B28', is_drum_available: false },
  { id: 'saasi-hydrous-52', product_id: '', name: 'Peacock Blue', code: '6355', hex: '#295F6C', is_drum_available: false },
  { id: 'saasi-hydrous-53', product_id: '', name: 'Lime', code: '6341', hex: '#D1E58B', is_drum_available: false },
  { id: 'saasi-hydrous-54', product_id: '', name: 'Honey Gold', code: '6334', hex: '#F8B56A', is_drum_available: false },
  { id: 'saasi-hydrous-55', product_id: '', name: 'Snowfield', code: '6358', hex: '#C0C8C8', is_drum_available: false },
  { id: 'saasi-hydrous-56', product_id: '', name: 'Green Land', code: '6348', hex: '#498242', is_drum_available: false },
  { id: 'saasi-hydrous-57', product_id: '', name: 'Dark Green', code: '6352', hex: '#214F33', is_drum_available: false },
  { id: 'saasi-hydrous-58', product_id: '', name: 'Grass Green', code: '6344', hex: '#7C9854', is_drum_available: false },
  { id: 'saasi-hydrous-59', product_id: '', name: 'Mango Yellow', code: '6338', hex: '#F6A841', is_drum_available: false },
];

export const SAASI_MATT_ENAMEL_SHADES: Shade[] = [
  // Image 1 - Warm Whites & Peachy tones
  { id: 'saasi-me-1', product_id: '', name: 'Milki White', code: '358', hex: '#FEF8E6', is_drum_available: false },
  { id: 'saasi-me-2', product_id: '', name: 'Kitten White', code: '353', hex: '#FCDECE', is_drum_available: false },
  { id: 'saasi-me-3', product_id: '', name: 'Peach', code: '346', hex: '#F5A987', is_drum_available: false },
  { id: 'saasi-me-4', product_id: '', name: 'Off White', code: '306', hex: '#FDF6D8', is_drum_available: false },
  { id: 'saasi-me-5', product_id: '', name: 'Rose White', code: '359', hex: '#F9CEBA', is_drum_available: false },
  { id: 'saasi-me-6', product_id: '', name: 'Natural Paprika', code: '320', hex: '#C96B4E', is_drum_available: false },
  { id: 'saasi-me-7', product_id: '', name: 'Cream', code: '301', hex: '#FDDCB0', is_drum_available: false },
  { id: 'saasi-me-8', product_id: '', name: 'Cameo', code: '352', hex: '#FBCBA0', is_drum_available: false },
  { id: 'saasi-me-9', product_id: '', name: 'Pumpkin', code: '338', hex: '#D45B35', is_drum_available: false },
  // Image 2 - Earthy, Warm & Vivid tones
  { id: 'saasi-me-10', product_id: '', name: 'Desert Tan', code: '387', hex: '#EBD8D0', is_drum_available: false },
  { id: 'saasi-me-11', product_id: '', name: 'Onion', code: '375', hex: '#F0E2D8', is_drum_available: false },
  { id: 'saasi-me-12', product_id: '', name: 'Shingle', code: '354', hex: '#F5C5C8', is_drum_available: false },
  { id: 'saasi-me-13', product_id: '', name: 'Lilac Bliss', code: '317', hex: '#C8BEDD', is_drum_available: false },
  { id: 'saasi-me-14', product_id: '', name: 'Bristoe Cream', code: '376', hex: '#F6E4DC', is_drum_available: false },
  { id: 'saasi-me-15', product_id: '', name: 'Beige Grey', code: '391', hex: '#C4B4B6', is_drum_available: false },
  { id: 'saasi-me-16', product_id: '', name: 'Puff', code: '325', hex: '#F4B8A0', is_drum_available: false },
  { id: 'saasi-me-17', product_id: '', name: 'Angel', code: '326', hex: '#F5C5C8', is_drum_available: false },
  { id: 'saasi-me-18', product_id: '', name: 'Purple Party', code: '357', hex: '#5A3060', is_drum_available: false },
  { id: 'saasi-me-19', product_id: '', name: 'Golden Brown', code: '379', hex: '#A05830', is_drum_available: false },
  { id: 'saasi-me-20', product_id: '', name: 'Gold Rust', code: '382', hex: '#C09030', is_drum_available: false },
  { id: 'saasi-me-21', product_id: '', name: 'Orange Grove', code: '380', hex: '#E8762A', is_drum_available: false },
  { id: 'saasi-me-22', product_id: '', name: 'Classical', code: '383', hex: '#D4A0A8', is_drum_available: false },
  { id: 'saasi-me-23', product_id: '', name: 'Bringal', code: '342', hex: '#4A1840', is_drum_available: false },
  { id: 'saasi-me-24', product_id: '', name: 'Chilli Red', code: '345', hex: '#9E2040', is_drum_available: false },
  { id: 'saasi-me-25', product_id: '', name: 'Gold', code: '381', hex: '#B0985A', is_drum_available: false },
  { id: 'saasi-me-26', product_id: '', name: 'Lemon', code: '334', hex: '#DDD020', is_drum_available: false },
  { id: 'saasi-me-27', product_id: '', name: 'Cameo Rose', code: '374', hex: '#E8809A', is_drum_available: false },
  { id: 'saasi-me-28', product_id: '', name: 'Carnival Pink', code: '341', hex: '#E02878', is_drum_available: false },
  { id: 'saasi-me-29', product_id: '', name: 'Sheesham', code: '388', hex: '#6B3820', is_drum_available: false },
  // Image 3 - Cool & Neutral tones
  { id: 'saasi-me-30', product_id: '', name: 'Ash White', code: '310', hex: '#E8E2D8', is_drum_available: false },
  { id: 'saasi-me-31', product_id: '', name: 'Snow Bell', code: '355', hex: '#C8C8CA', is_drum_available: false },
  { id: 'saasi-me-32', product_id: '', name: 'Torres Blue', code: '321', hex: '#89B8D8', is_drum_available: false },
  { id: 'saasi-me-33', product_id: '', name: 'Cool Blue', code: '322', hex: '#6098BC', is_drum_available: false },
  { id: 'saasi-me-34', product_id: '', name: 'Reflection', code: '313', hex: '#A8D4C0', is_drum_available: false },
  { id: 'saasi-me-35', product_id: '', name: 'Antique White', code: '350', hex: '#F2EDDA', is_drum_available: false },
  { id: 'saasi-me-36', product_id: '', name: 'Lavender White', code: '328', hex: '#ABABAF', is_drum_available: false },
  { id: 'saasi-me-37', product_id: '', name: 'First Dawn', code: '327', hex: '#3C72A8', is_drum_available: false },
  { id: 'saasi-me-38', product_id: '', name: 'Ocean Dip', code: '386', hex: '#1E7890', is_drum_available: false },
  { id: 'saasi-me-39', product_id: '', name: 'Sea Green', code: '324', hex: '#88C8A4', is_drum_available: false },
  { id: 'saasi-me-40', product_id: '', name: 'Chandni', code: '389', hex: '#EEE8D4', is_drum_available: false },
  { id: 'saasi-me-41', product_id: '', name: 'Steel Grey', code: '390', hex: '#787A7C', is_drum_available: false },
  { id: 'saasi-me-42', product_id: '', name: 'Fresh Lime', code: '384', hex: '#A8AA40', is_drum_available: false },
  { id: 'saasi-me-43', product_id: '', name: 'White Ice', code: '361', hex: '#EEF0E8', is_drum_available: false },
  { id: 'saasi-me-44', product_id: '', name: 'Navy Blue', code: '336', hex: '#1C2E68', is_drum_available: false },
  { id: 'saasi-me-45', product_id: '', name: 'Pennant', code: '385', hex: '#00A8A8', is_drum_available: false },
];

export const SAASI_PLASTIC_EMULSION_SHADES: Shade[] = [
  // Manually Added
  { id: 'saasi-pe-61', product_id: '', name: 'Brilliant White', code: '100', hex: '#FFFFFF', is_drum_available: true },

  // Image 1 - Warm/Neutral Whites
  { id: 'saasi-pe-1', product_id: '', name: 'Off White', code: '104', hex: '#FDF6D8', is_drum_available: true },
  { id: 'saasi-pe-2', product_id: '', name: 'Old Off White', code: '101', hex: '#FDF4E3', is_drum_available: true },
  { id: 'saasi-pe-3', product_id: '', name: 'Antique White', code: '184', hex: '#F2EDDA', is_drum_available: false },
  { id: 'saasi-pe-4', product_id: '', name: 'Milkey White', code: '105', hex: '#FEF8E6', is_drum_available: true },
  { id: 'saasi-pe-5', product_id: '', name: 'Chandni', code: '106', hex: '#EEE8D4', is_drum_available: false },
  { id: 'saasi-pe-6', product_id: '', name: 'Lemon', code: '158', hex: '#DDD020', is_drum_available: false },
  { id: 'saasi-pe-7', product_id: '', name: 'Sage Garden', code: '189', hex: '#EAE3BA', is_drum_available: false },
  { id: 'saasi-pe-8', product_id: '', name: 'Cockle Shell', code: '162', hex: '#EBE4D0', is_drum_available: true },
  { id: 'saasi-pe-9', product_id: '', name: 'Desert Dawn', code: '185', hex: '#F4B8A0', is_drum_available: false },
  { id: 'saasi-pe-10', product_id: '', name: 'Sugar Cane', code: '123', hex: '#FDDCB0', is_drum_available: false },
  { id: 'saasi-pe-11', product_id: '', name: 'Cameo', code: '167', hex: '#FBCBA0', is_drum_available: true },
  { id: 'saasi-pe-12', product_id: '', name: 'Paprika', code: '193', hex: '#C96B4E', is_drum_available: false },

  // Image 2 - Pink/Red/Earth
  { id: 'saasi-pe-13', product_id: '', name: 'Blossom Pink', code: '192', hex: '#F5C5C8', is_drum_available: false },
  { id: 'saasi-pe-14', product_id: '', name: 'Moon Flower', code: '108', hex: '#F9D8D2', is_drum_available: true },
  { id: 'saasi-pe-15', product_id: '', name: 'Pink Violet', code: '187', hex: '#E297C1', is_drum_available: false },
  { id: 'saasi-pe-16', product_id: '', name: 'Badami', code: '107', hex: '#DED9D4', is_drum_available: true },
  { id: 'saasi-pe-17', product_id: '', name: 'Cozy', code: '186', hex: '#F6E4DC', is_drum_available: false },
  { id: 'saasi-pe-18', product_id: '', name: 'Rose Mist', code: '102', hex: '#F9CEBA', is_drum_available: true },
  { id: 'saasi-pe-19', product_id: '', name: 'Pink', code: '111', hex: '#F5C2CD', is_drum_available: false },
  { id: 'saasi-pe-20', product_id: '', name: 'Carnival Pink', code: '194', hex: '#E02878', is_drum_available: false },
  { id: 'saasi-pe-21', product_id: '', name: 'Sand Stone', code: '150', hex: '#CBC2B1', is_drum_available: false },
  { id: 'saasi-pe-22', product_id: '', name: 'Peach', code: '103', hex: '#F8D1B4', is_drum_available: true },
  { id: 'saasi-pe-23', product_id: '', name: 'Bliss', code: '146', hex: '#F5C5C8', is_drum_available: false },
  { id: 'saasi-pe-24', product_id: '', name: 'Angel', code: '148', hex: '#EBD8D0', is_drum_available: false },
  { id: 'saasi-pe-25', product_id: '', name: 'Tile Red', code: '163', hex: '#872E31', is_drum_available: false },
  { id: 'saasi-pe-26', product_id: '', name: 'Hopsack', code: '112', hex: '#A6805D', is_drum_available: true },
  { id: 'saasi-pe-27', product_id: '', name: 'Sunset', code: '195', hex: '#A05830', is_drum_available: false },
  { id: 'saasi-pe-28', product_id: '', name: 'Orange', code: '169', hex: '#E8762A', is_drum_available: false },
  { id: 'saasi-pe-29', product_id: '', name: 'Swiss Miss', code: '182', hex: '#D4A0A8', is_drum_available: false },
  { id: 'saasi-pe-30', product_id: '', name: 'Adventure', code: '115', hex: '#3E6B9D', is_drum_available: false },
  { id: 'saasi-pe-31', product_id: '', name: 'Woven Green', code: '190', hex: '#B0985A', is_drum_available: false },
  { id: 'saasi-pe-32', product_id: '', name: 'Terracotta', code: '196', hex: '#6B3820', is_drum_available: false },
  { id: 'saasi-pe-33', product_id: '', name: 'Red Oxide', code: '191', hex: '#5C4530', is_drum_available: false },
  { id: 'saasi-pe-34', product_id: '', name: 'Saasi Pink', code: '183', hex: '#E8809A', is_drum_available: false },
  { id: 'saasi-pe-35', product_id: '', name: 'Chilli Red', code: '168', hex: '#9E2040', is_drum_available: false },

  // Image 3 - Cool/Blue/Green
  { id: 'saasi-pe-36', product_id: '', name: 'Ash White', code: '120', hex: '#E8E2D8', is_drum_available: true },
  { id: 'saasi-pe-37', product_id: '', name: 'White Pepper', code: '174', hex: '#F0E2D8', is_drum_available: false },
  { id: 'saasi-pe-38', product_id: '', name: 'Lilac', code: '125', hex: '#C8C8CA', is_drum_available: true },
  { id: 'saasi-pe-39', product_id: '', name: 'Crystal Green', code: '161', hex: '#A8D4C0', is_drum_available: false },
  { id: 'saasi-pe-40', product_id: '', name: 'Torres Blue', code: '153', hex: '#89B8D8', is_drum_available: true },
  { id: 'saasi-pe-41', product_id: '', name: 'New Ash White', code: '116', hex: '#DED9D4', is_drum_available: true },
  { id: 'saasi-pe-42', product_id: '', name: 'Twilight', code: '175', hex: '#85D4F5', is_drum_available: false },
  { id: 'saasi-pe-43', product_id: '', name: 'Parasol', code: '173', hex: '#E0CFD8', is_drum_available: false },
  { id: 'saasi-pe-44', product_id: '', name: 'Ice Flow', code: '109', hex: '#DED9D4', is_drum_available: false },
  { id: 'saasi-pe-45', product_id: '', name: 'Charisma White', code: '156', hex: '#B4B9D6', is_drum_available: false },
  { id: 'saasi-pe-46', product_id: '', name: 'Ash Grey', code: '159', hex: '#8A8E89', is_drum_available: false },
  { id: 'saasi-pe-47', product_id: '', name: 'Lavender White', code: '151', hex: '#ABABAF', is_drum_available: true },
  { id: 'saasi-pe-48', product_id: '', name: 'Lavender', code: '152', hex: '#B4B9D6', is_drum_available: false },
  { id: 'saasi-pe-49', product_id: '', name: 'Apple Green', code: '166', hex: '#88C8A4', is_drum_available: false },
  { id: 'saasi-pe-50', product_id: '', name: 'Sea Blue', code: '197', hex: '#1E7890', is_drum_available: false },
  { id: 'saasi-pe-51', product_id: '', name: 'Chocolate', code: '172', hex: '#352B28', is_drum_available: false },
  { id: 'saasi-pe-52', product_id: '', name: 'Grey White', code: '155', hex: '#EEE8D4', is_drum_available: false },
  { id: 'saasi-pe-53', product_id: '', name: 'Violet', code: '137', hex: '#4C3C58', is_drum_available: false },
  { id: 'saasi-pe-54', product_id: '', name: 'Lime Frost', code: '117', hex: '#A8AA40', is_drum_available: false },
  { id: 'saasi-pe-55', product_id: '', name: 'Bright Blue', code: '165', hex: '#3C72A8', is_drum_available: false },
  { id: 'saasi-pe-56', product_id: '', name: 'Goose Wing', code: '114', hex: '#787A7C', is_drum_available: false },
  { id: 'saasi-pe-57', product_id: '', name: 'Whisper', code: '164', hex: '#EEE8D4', is_drum_available: false },
  { id: 'saasi-pe-58', product_id: '', name: 'Leaf Green', code: '171', hex: '#498242', is_drum_available: false },
  { id: 'saasi-pe-59', product_id: '', name: 'Green Summit', code: '176', hex: '#AFD38E', is_drum_available: false },
  { id: 'saasi-pe-60', product_id: '', name: 'Indigo', code: '170', hex: '#1C2E68', is_drum_available: false },
];

export const SAASI_SUPER_GLOSS_ENAMEL_SHADES: Shade[] = [
  // Manually Added
  { id: 'saasi-sge-60', product_id: '', name: 'Brilliant White', code: '200', hex: '#FFFFFF', is_drum_available: true },

  // Image 1 - Warm/Cream/Peach
  { id: 'saasi-sge-1', product_id: '', name: 'Riesling', code: '252', hex: '#FDF7E2', is_drum_available: false },
  { id: 'saasi-sge-2', product_id: '', name: 'Butter Corn', code: '251', hex: '#FCE0A1', is_drum_available: false },
  { id: 'saasi-sge-3', product_id: '', name: 'Peach', code: '236', hex: '#F8B595', is_drum_available: false },
  { id: 'saasi-sge-4', product_id: '', name: 'Off White', code: '201', hex: '#FDF4E3', is_drum_available: true },
  { id: 'saasi-sge-5', product_id: '', name: 'County Cream', code: '202', hex: '#F8D18C', is_drum_available: true },
  { id: 'saasi-sge-6', product_id: '', name: 'Cameo', code: '232', hex: '#FBCBA0', is_drum_available: false },
  { id: 'saasi-sge-7', product_id: '', name: 'Sea Oats', code: '250', hex: '#F9EED1', is_drum_available: false },
  { id: 'saasi-sge-8', product_id: '', name: 'Diyar', code: '259', hex: '#E2BF9C', is_drum_available: false },
  { id: 'saasi-sge-9', product_id: '', name: 'Soft Terracotta', code: '225', hex: '#F9AC8D', is_drum_available: false },
  { id: 'saasi-sge-10', product_id: '', name: 'Early Dawn', code: '221', hex: '#FEE5D9', is_drum_available: false },
  { id: 'saasi-sge-11', product_id: '', name: 'Caramel', code: '226', hex: '#D78E29', is_drum_available: false },
  { id: 'saasi-sge-12', product_id: '', name: 'Terracotta', code: '260', hex: '#D29783', is_drum_available: false },

  // Image 2 - Mid Tones
  { id: 'saasi-sge-13', product_id: '', name: 'Blush Pink', code: '205', hex: '#F9D8D2', is_drum_available: false },
  { id: 'saasi-sge-14', product_id: '', name: 'Dream Land', code: '224', hex: '#E4EFDC', is_drum_available: false },
  { id: 'saasi-sge-15', product_id: '', name: 'Beige', code: '203', hex: '#BC9F79', is_drum_available: false },
  { id: 'saasi-sge-16', product_id: '', name: 'Orange', code: '243', hex: '#E74323', is_drum_available: false },
  { id: 'saasi-sge-17', product_id: '', name: 'Lilac Touch', code: '238', hex: '#DFD8EB', is_drum_available: false },
  { id: 'saasi-sge-18', product_id: '', name: 'Angel', code: '233', hex: '#F5C2CD', is_drum_available: false },
  { id: 'saasi-sge-19', product_id: '', name: 'Sea Green', code: '216', hex: '#80B98E', is_drum_available: true },
  { id: 'saasi-sge-20', product_id: '', name: 'Coriander', code: '242', hex: '#A47D75', is_drum_available: false },
  { id: 'saasi-sge-21', product_id: '', name: 'Golden Brown', code: '207', hex: '#955034', is_drum_available: false },
  { id: 'saasi-sge-22', product_id: '', name: 'Mauve', code: '219', hex: '#AFA4CC', is_drum_available: false },
  { id: 'saasi-sge-23', product_id: '', name: 'Rose Bouquet', code: '255', hex: '#F599AC', is_drum_available: false },
  { id: 'saasi-sge-24', product_id: '', name: 'Green Dream', code: '259', hex: '#44A89C', is_drum_available: false },
  { id: 'saasi-sge-25', product_id: '', name: 'Red Oxide', code: '217', hex: '#3B1213', is_drum_available: true },
  { id: 'saasi-sge-26', product_id: '', name: 'Oyster', code: '223', hex: '#D2D1BF', is_drum_available: false },
  { id: 'saasi-sge-27', product_id: '', name: 'Slate Grey', code: '227', hex: '#929B9C', is_drum_available: false },
  { id: 'saasi-sge-28', product_id: '', name: 'Sweet William', code: '257', hex: '#E6B4CE', is_drum_available: false },
  { id: 'saasi-sge-29', product_id: '', name: 'Adams Green', code: '261', hex: '#34A086', is_drum_available: false },
  { id: 'saasi-sge-30', product_id: '', name: 'Colombian Coffee', code: '258', hex: '#4B3131', is_drum_available: false },
  { id: 'saasi-sge-31', product_id: '', name: 'Crimson', code: '234', hex: '#4E0A0C', is_drum_available: false },
  { id: 'saasi-sge-32', product_id: '', name: 'Dark Grey', code: '231', hex: '#34383F', is_drum_available: false },
  { id: 'saasi-sge-33', product_id: '', name: 'Carnival Pink', code: '256', hex: '#B8456D', is_drum_available: false },
  { id: 'saasi-sge-34', product_id: '', name: 'Signal Green', code: '218', hex: '#0B1D16', is_drum_available: true },

  // Image 3 - Neutrals/Blue/Strong
  { id: 'saasi-sge-35', product_id: '', name: 'Ash White', code: '209', hex: '#EBE4D0', is_drum_available: true },
  { id: 'saasi-sge-36', product_id: '', name: 'Pumice', code: '263', hex: '#CCD6D7', is_drum_available: false },
  { id: 'saasi-sge-37', product_id: '', name: 'Polish Brown', code: '253', hex: '#B26231', is_drum_available: false },
  { id: 'saasi-sge-38', product_id: '', name: 'Mustard', code: '265', hex: '#BE9151', is_drum_available: false },
  { id: 'saasi-sge-39', product_id: '', name: 'Sky Blue', code: '214', hex: '#AED6EB', is_drum_available: true },
  { id: 'saasi-sge-40', product_id: '', name: 'Dove Grey', code: '210', hex: '#C0C8C8', is_drum_available: true },
  { id: 'saasi-sge-41', product_id: '', name: 'Torres Blue', code: '235', hex: '#C7DAEA', is_drum_available: false },
  { id: 'saasi-sge-42', product_id: '', name: 'Ochre', code: '254', hex: '#C36437', is_drum_available: false },
  { id: 'saasi-sge-43', product_id: '', name: 'New Polish Brown', code: '266', hex: '#A37250', is_drum_available: false },
  { id: 'saasi-sge-44', product_id: '', name: 'Light Blue', code: '215', hex: '#87C3EA', is_drum_available: true },
  { id: 'saasi-sge-45', product_id: '', name: 'Ash Grey', code: '211', hex: '#BDBDBA', is_drum_available: true },
  { id: 'saasi-sge-46', product_id: '', name: 'Smoke Grey', code: '212', hex: '#3E546C', is_drum_available: true },
  { id: 'saasi-sge-47', product_id: '', name: 'Lemon', code: '228', hex: '#FDD521', is_drum_available: false },
  { id: 'saasi-sge-48', product_id: '', name: 'Brown', code: '267', hex: '#633D2D', is_drum_available: false },
  { id: 'saasi-sge-49', product_id: '', name: 'Vivid Blue', code: '241', hex: '#0076B8', is_drum_available: false },
  { id: 'saasi-sge-50', product_id: '', name: 'Court Grey', code: '220', hex: '#A9ABAA', is_drum_available: false },
  { id: 'saasi-sge-51', product_id: '', name: 'Champagne', code: '204', hex: '#84735E', is_drum_available: false },
  { id: 'saasi-sge-52', product_id: '', name: 'Golden Yellow', code: '208', hex: '#FC9D1B', is_drum_available: false },
  { id: 'saasi-sge-53', product_id: '', name: 'Signal Red', code: '206', hex: '#95161B', is_drum_available: true },
  { id: 'saasi-sge-54', product_id: '', name: 'Middle Blue', code: '213', hex: '#1E3E7F', is_drum_available: true },
  { id: 'saasi-sge-55', product_id: '', name: 'Light Grey', code: '262', hex: '#94A6A2', is_drum_available: false },
  { id: 'saasi-sge-56', product_id: '', name: 'Bahama Brown', code: '240', hex: '#30221E', is_drum_available: false },
  { id: 'saasi-sge-57', product_id: '', name: 'Yellow', code: '264', hex: '#F99521', is_drum_available: false },
  { id: 'saasi-sge-58', product_id: '', name: 'Leather Brown', code: '222', hex: '#111111', is_drum_available: true },
  { id: 'saasi-sge-59', product_id: '', name: 'Black', code: '229', hex: '#000000', is_drum_available: true },
];

export const SAASI_WEATHER_SAFE_SHADES: Shade[] = [
  // Manually Added
  { id: 'saasi-ws-62', product_id: '', name: 'Brilliant White', code: '(400) 1000', hex: '#FFFFFF', is_drum_available: true },

  // Image 1
  { id: 'saasi-ws-1', product_id: '', name: 'Off White', code: '(401) 1952', hex: '#FDF6D8', is_drum_available: true },
  { id: 'saasi-ws-2', product_id: '', name: 'Ivory Silk', code: '(436) 6108', hex: '#F2EDDA', is_drum_available: false },
  { id: 'saasi-ws-3', product_id: '', name: 'Barber Beige', code: '(430) 2891', hex: '#FDF4E3', is_drum_available: true },
  { id: 'saasi-ws-4', product_id: '', name: 'Almond Whisper', code: '(435) 6107', hex: '#FEF8E6', is_drum_available: false },
  { id: 'saasi-ws-5', product_id: '', name: 'Sand Stone', code: '(411) 1949', hex: '#CBC2B1', is_drum_available: false },
  { id: 'saasi-ws-6', product_id: '', name: 'Apricot', code: '(410) 1920', hex: '#F8D1B4', is_drum_available: true },
  { id: 'saasi-ws-7', product_id: '', name: 'Cameo', code: '(421) 2685', hex: '#FBCBA0', is_drum_available: false },
  { id: 'saasi-ws-8', product_id: '', name: 'Beige', code: '(414) 2087', hex: '#BC9F79', is_drum_available: true },
  { id: 'saasi-ws-9', product_id: '', name: 'Sweet Jewel', code: '(432) 4058', hex: '#F9AC8D', is_drum_available: false },
  { id: 'saasi-ws-10', product_id: '', name: 'Sharp Cameo', code: '(439) 6826', hex: '#E2BF9C', is_drum_available: false },
  { id: 'saasi-ws-11', product_id: '', name: 'Sun Shower', code: '(449) 6849', hex: '#F9EED1', is_drum_available: false },

  // Image 2
  { id: 'saasi-ws-12', product_id: '', name: 'Ash White', code: '5081', hex: '#E8E2D8', is_drum_available: true },
  { id: 'saasi-ws-13', product_id: '', name: 'Sea Lock', code: '(417) 2465', hex: '#A8D4C0', is_drum_available: false },
  { id: 'saasi-ws-14', product_id: '', name: 'Weak Tea', code: '(433) 5055', hex: '#F9D8D2', is_drum_available: false },
  { id: 'saasi-ws-15', product_id: '', name: 'Fruity', code: '(420) 081', hex: '#FCE0A1', is_drum_available: false },
  { id: 'saasi-ws-16', product_id: '', name: 'Roof Tile', code: '(416) 2111', hex: '#872E31', is_drum_available: false },
  { id: 'saasi-ws-17', product_id: '', name: 'Badami', code: '(438) 6183', hex: '#DED9D4', is_drum_available: true },
  { id: 'saasi-ws-18', product_id: '', name: 'Vivid', code: '(418) 2468', hex: '#3E6B9D', is_drum_available: false },
  { id: 'saasi-ws-19', product_id: '', name: 'Pink Pavilion', code: '(437) 6172', hex: '#F5C5C8', is_drum_available: false },
  { id: 'saasi-ws-20', product_id: '', name: 'Mehndi', code: '(405) 0170', hex: '#B0985A', is_drum_available: false },
  { id: 'saasi-ws-21', product_id: '', name: 'Red Oxide', code: '(426) 2910', hex: '#5C4530', is_drum_available: true },
  { id: 'saasi-ws-22', product_id: '', name: 'Tea Rose', code: '(412) 1958', hex: '#E0CFD8', is_drum_available: false },
  { id: 'saasi-ws-23', product_id: '', name: 'Ocean Wave', code: '(427) 2983', hex: '#89B8D8', is_drum_available: false },
  { id: 'saasi-ws-24', product_id: '', name: 'Cappuccino', code: '(404) 0161', hex: '#A6805D', is_drum_available: false },
  { id: 'saasi-ws-25', product_id: '', name: 'Red Haze', code: '5082', hex: '#E74323', is_drum_available: false },
  { id: 'saasi-ws-26', product_id: '', name: 'Chocolate', code: '(407) 0175', hex: '#352B28', is_drum_available: true },
  { id: 'saasi-ws-27', product_id: '', name: 'Desert Dawn', code: '(450) 7049', hex: '#F4B8A0', is_drum_available: false },
  { id: 'saasi-ws-28', product_id: '', name: 'Sharp Blue', code: '093', hex: '#1E7890', is_drum_available: false },
  { id: 'saasi-ws-29', product_id: '', name: 'Avocado', code: '(415) 2088', hex: '#88C8A4', is_drum_available: false },
  { id: 'saasi-ws-30', product_id: '', name: 'Orange', code: '(456) 3050', hex: '#E8762A', is_drum_available: false },
  { id: 'saasi-ws-31', product_id: '', name: 'Evening Shadow', code: '5083', hex: '#34383F', is_drum_available: false },
  { id: 'saasi-ws-32', product_id: '', name: 'Peach', code: '(431) 3165', hex: '#F8D1B4', is_drum_available: true },
  { id: 'saasi-ws-33', product_id: '', name: 'Blue Magic', code: '(453) 3032', hex: '#1C2E68', is_drum_available: false },
  { id: 'saasi-ws-34', product_id: '', name: 'Admiral', code: '(424) 2886', hex: '#3C72A8', is_drum_available: false },
  { id: 'saasi-ws-35', product_id: '', name: 'Red Rose', code: '(441) 0141', hex: '#9E2040', is_drum_available: false },
  { id: 'saasi-ws-36', product_id: '', name: 'Black', code: '5084', hex: '#000000', is_drum_available: true },

  // Image 3
  { id: 'saasi-ws-37', product_id: '', name: 'Ash White', code: '(402) 1919', hex: '#E8E2D8', is_drum_available: true },
  { id: 'saasi-ws-38', product_id: '', name: 'Portland', code: '(422) 2688', hex: '#CCD6D7', is_drum_available: false },
  { id: 'saasi-ws-39', product_id: '', name: 'Ash Grey', code: '(446) 5002', hex: '#8A8E89', is_drum_available: false },
  { id: 'saasi-ws-40', product_id: '', name: 'Terracotta', code: '(429) 3148', hex: '#6B3820', is_drum_available: false },
  { id: 'saasi-ws-41', product_id: '', name: 'Clay', code: '(428) 3145', hex: '#929B9C', is_drum_available: false },
  { id: 'saasi-ws-42', product_id: '', name: 'Grey White', code: '455', hex: '#BDBDBA', is_drum_available: true },
  { id: 'saasi-ws-43', product_id: '', name: 'Moor Land', code: '(451) 3045', hex: '#80B98E', is_drum_available: false },
  { id: 'saasi-ws-44', product_id: '', name: 'Stone Grey', code: '(445) 5023', hex: '#787A7C', is_drum_available: false },
  { id: 'saasi-ws-45', product_id: '', name: 'Multani Tile', code: '(434) 5354', hex: '#A37250', is_drum_available: false },
  { id: 'saasi-ws-46', product_id: '', name: 'Avocado', code: '5086', hex: '#498242', is_drum_available: false },
  { id: 'saasi-ws-47', product_id: '', name: 'Sky Grey', code: '(425) 3160', hex: '#A9ABAA', is_drum_available: false },
  { id: 'saasi-ws-48', product_id: '', name: 'Grey Tile', code: '(442) 5079', hex: '#94A6A2', is_drum_available: false },
  { id: 'saasi-ws-49', product_id: '', name: 'Antelope', code: '(419) 2683', hex: '#84735E', is_drum_available: false },
  { id: 'saasi-ws-50', product_id: '', name: 'Spicy Orange', code: '(406) 0171', hex: '#C36437', is_drum_available: false },
  { id: 'saasi-ws-51', product_id: '', name: 'Tile Red', code: '(447) 0113', hex: '#95161B', is_drum_available: true },
  { id: 'saasi-ws-52', product_id: '', name: 'Goose Wing', code: '(413) 1959', hex: '#DED9D4', is_drum_available: false },
  { id: 'saasi-ws-53', product_id: '', name: 'Ocean Storm', code: '(443) 0178', hex: '#C7DAEA', is_drum_available: false },
  { id: 'saasi-ws-54', product_id: '', name: 'Nutty Brown', code: '(452) 3049', hex: '#633D2D', is_drum_available: false },
  { id: 'saasi-ws-55', product_id: '', name: 'Chilli Red', code: '(408) 0176', hex: '#9E2040', is_drum_available: false },
  { id: 'saasi-ws-56', product_id: '', name: 'Khaprail', code: '5087', hex: '#5C4530', is_drum_available: false },
  { id: 'saasi-ws-57', product_id: '', name: 'Charcoal', code: '(454) 3127', hex: '#34383F', is_drum_available: false },
  { id: 'saasi-ws-58', product_id: '', name: 'Wirework Grey', code: '5080', hex: '#BDBDBA', is_drum_available: true },
  { id: 'saasi-ws-59', product_id: '', name: 'Chocolate', code: '5085', hex: '#352B28', is_drum_available: true },
  { id: 'saasi-ws-60', product_id: '', name: 'Spice', code: '(448) 014', hex: '#BC9F79', is_drum_available: false },
  { id: 'saasi-ws-61', product_id: '', name: 'Autumn Red', code: '5088', hex: '#872E31', is_drum_available: false },
];

export const GOBIS_INDUSTRIAL_ENAMEL_SHADES: Shade[] = [
  { id: 'gi-9000', product_id: '', name: 'Brilliant White', code: '9000', hex: '#FFFFFF', is_drum_available: false },
  { id: 'gi-9001', product_id: '', name: 'Off White', code: '9001', hex: '#FAF9F6', is_drum_available: false },
  { id: 'gi-9002', product_id: '', name: 'Ash White', code: '9002', hex: '#F2F2F2', is_drum_available: false },
  { id: 'gi-9003', product_id: '', name: 'Light Grey', code: '9003', hex: '#D3D3D3', is_drum_available: false },
  { id: 'gi-9004', product_id: '', name: 'Soft Ivory', code: '9004', hex: '#FFFDD0', is_drum_available: false },
  { id: 'gi-9005', product_id: '', name: 'Soft Beige', code: '9005', hex: '#F5F5DC', is_drum_available: false },
  { id: 'gi-9006', product_id: '', name: 'Beige', code: '9006', hex: '#D4B896', is_drum_available: false },
  { id: 'gi-9007', product_id: '', name: 'Dark Mushroom', code: '9007', hex: '#8D735D', is_drum_available: false },
  { id: 'gi-9008', product_id: '', name: 'Silver Grey', code: '9008', hex: '#C0C0C0', is_drum_available: false },
  { id: 'gi-9009', product_id: '', name: 'Pak Grey', code: '9009', hex: '#A9A9A9', is_drum_available: false },
  { id: 'gi-9010', product_id: '', name: 'Tank Red', code: '9010', hex: '#B22222', is_drum_available: false },
  { id: 'gi-9011', product_id: '', name: 'Jet Green', code: '9011', hex: '#006400', is_drum_available: false },
  { id: 'gi-9012', product_id: '', name: 'Stone Green', code: '9012', hex: '#2E8B57', is_drum_available: false },
  { id: 'gi-9013', product_id: '', name: 'Trans Blue', code: '9013', hex: '#000080', is_drum_available: false },
  { id: 'gi-9014', product_id: '', name: 'Smoke Grey', code: '9014', hex: '#708090', is_drum_available: false },
  { id: 'gi-9015', product_id: '', name: 'D. Grey (New)', code: '9015', hex: '#4F4F4F', is_drum_available: false },
  { id: 'gi-9016', product_id: '', name: 'M.B Green', code: '9016', hex: '#355E3B', is_drum_available: false },
  { id: 'gi-9017', product_id: '', name: 'Army Green', code: '9017', hex: '#4B5320', is_drum_available: false },
  { id: 'gi-9018', product_id: '', name: 'Adam Green', code: '9018', hex: '#355E3B', is_drum_available: false },
  { id: 'gi-9019', product_id: '', name: 'Emerald', code: '9019', hex: '#50C878', is_drum_available: false },
  { id: 'gi-9020', product_id: '', name: 'Champagne', code: '9020', hex: '#F7E7CE', is_drum_available: false },
  { id: 'gi-9021', product_id: '', name: 'Mauve', code: '9021', hex: '#E0B0FF', is_drum_available: false },
  { id: 'gi-9022', product_id: '', name: 'Brown', code: '9022', hex: '#654321', is_drum_available: false },
  { id: 'gi-9023', product_id: '', name: 'Golden Brown', code: '9023', hex: '#996515', is_drum_available: false },
  { id: 'gi-9024', product_id: '', name: 'Red Oxide', code: '9024', hex: '#6D1008', is_drum_available: false },
  { id: 'gi-9025', product_id: '', name: 'Coriander', code: '9025', hex: '#8B8B00', is_drum_available: false },
  { id: 'gi-9026', product_id: '', name: 'Orange', code: '9026', hex: '#FF8C00', is_drum_available: false },
  { id: 'gi-9027', product_id: '', name: 'Signal Red', code: '9027', hex: '#FF0000', is_drum_available: false },
  { id: 'gi-9028', product_id: '', name: 'Golden Yellow', code: '9028', hex: '#FFD700', is_drum_available: false },
  { id: 'gi-9029', product_id: '', name: 'Lemon Yellow', code: '9029', hex: '#FFF44F', is_drum_available: false },
  { id: 'gi-9030', product_id: '', name: 'Hot Pink', code: '9030', hex: '#FF69B4', is_drum_available: false },
  { id: 'gi-9031', product_id: '', name: 'H. R Blue', code: '9031', hex: '#003399', is_drum_available: false },
  { id: 'gi-9032', product_id: '', name: 'Vivid Blue', code: '9032', hex: '#1E90FF', is_drum_available: false },
  { id: 'gi-9033', product_id: '', name: 'Violet', code: '9033', hex: '#8B00FF', is_drum_available: false },
  { id: 'gi-9034', product_id: '', name: 'Edu-De-Nill', code: '9034', hex: '#99C5C4', is_drum_available: false },
  { id: 'gi-9035', product_id: '', name: 'Desert Sand', code: '9035', hex: '#EDC9AF', is_drum_available: false },
  { id: 'gi-9036', product_id: '', name: 'Dark Brown', code: '9036', hex: '#5C4033', is_drum_available: false },
  { id: 'gi-9037', product_id: '', name: 'Royal Green', code: '9037', hex: '#136207', is_drum_available: false },
  { id: 'gi-9038', product_id: '', name: 'Blue', code: '9038', hex: '#0000FF', is_drum_available: false },
  { id: 'gi-9039', product_id: '', name: 'Maroon', code: '9039', hex: '#800000', is_drum_available: false },
  { id: 'gi-9040', product_id: '', name: 'Green', code: '9040', hex: '#008000', is_drum_available: false },
  { id: 'gi-9041', product_id: '', name: 'Intense Violet', code: '9041', hex: '#7F00FF', is_drum_available: false },
  { id: 'gi-9042', product_id: '', name: 'Copper', code: '9042', hex: '#B87333', is_drum_available: false },
  { id: 'gi-9043', product_id: '', name: 'Black', code: '9043', hex: '#000000', is_drum_available: false },
  { id: 'gi-9044', product_id: '', name: 'Classic Beige', code: '9044', hex: '#F5F5DC', is_drum_available: false },
  { id: 'gi-9045', product_id: '', name: 'Gold', code: '9045', hex: '#FFD700', is_drum_available: false },
  { id: 'gi-9046', product_id: '', name: 'Shiny Green', code: '9046', hex: '#00FF7F', is_drum_available: false },
  { id: 'gi-9047', product_id: '', name: 'Iceland Blue', code: '9047', hex: '#ADD8E6', is_drum_available: false },
  { id: 'gi-9048', product_id: '', name: 'Silver', code: '9048', hex: '#C0C0C0', is_drum_available: false },
];

export const GOBIS_STOVING_PAINT_SHADES: Shade[] = [
  { id: 'gs-8131', product_id: '', name: 'Major Ivory', code: '8131', hex: '#F3E5AB', is_drum_available: false },
  { id: 'gs-8160', product_id: '', name: 'Polish Brown', code: '8160', hex: '#A37250', is_drum_available: false },
  { id: 'gs-8113', product_id: '', name: 'Signal Red', code: '8113', hex: '#FF0000', is_drum_available: false },
  { id: 'gs-8104', product_id: '', name: 'Lemon Yellow', code: '8104', hex: '#FFF44F', is_drum_available: false },
  { id: 'gs-8142', product_id: '', name: 'Honda Blue', code: '8142', hex: '#00529B', is_drum_available: false },
  { id: 'gs-8124', product_id: '', name: 'Light Green', code: '8124', hex: '#90EE90', is_drum_available: false },
  { id: 'gs-8117', product_id: '', name: 'Gob Beige', code: '8117', hex: '#F5F5DC', is_drum_available: false },
  { id: 'gs-8110', product_id: '', name: 'Brown', code: '8110', hex: '#8B4513', is_drum_available: false },
  { id: 'gs-8114', product_id: '', name: 'P.O.Red', code: '8114', hex: '#BF0A30', is_drum_available: false },
  { id: 'gs-8156', product_id: '', name: 'Golden Yellow', code: '8156', hex: '#FFD700', is_drum_available: false },
  { id: 'gs-8174', product_id: '', name: 'Filter Blue', code: '8174', hex: '#1CA9C9', is_drum_available: false },
  { id: 'gs-8127', product_id: '', name: 'Spring Green', code: '8127', hex: '#00FF7F', is_drum_available: false },
  { id: 'gs-8118', product_id: '', name: 'Gaz. Beige', code: '8118', hex: '#D2B48C', is_drum_available: false },
  { id: 'gs-8133', product_id: '', name: 'Maroon', code: '8133', hex: '#800000', is_drum_available: false },
  { id: 'gs-8188', product_id: '', name: 'Tank Red', code: '8188', hex: '#B22222', is_drum_available: false },
  { id: 'gs-8157', product_id: '', name: 'Rekshaw Yellow', code: '8157', hex: '#FFDB58', is_drum_available: false },
  { id: 'gs-8162', product_id: '', name: 'Original Green', code: '8162', hex: '#008000', is_drum_available: false },
  { id: 'gs-8178', product_id: '', name: 'Gob Grey', code: '8178', hex: '#808080', is_drum_available: false },
  { id: 'gs-8407', product_id: '', name: 'Off White', code: '8407', hex: '#FAF9F6', is_drum_available: false },
  { id: 'gs-8204', product_id: '', name: 'Mid Grey', code: '8204', hex: '#A9A9A9', is_drum_available: false },
  { id: 'gs-8202', product_id: '', name: 'Beige', code: '8202', hex: '#F5F5DC', is_drum_available: false },
  { id: 'gs-8184', product_id: '', name: 'Steel Grey', code: '8184', hex: '#778899', is_drum_available: false },
  { id: 'gs-8491', product_id: '', name: 'Soft Ivory R', code: '8491', hex: '#C4A882', is_drum_available: false },
  { id: 'gs-8203', product_id: '', name: 'Dark Grey', code: '8203', hex: '#555555', is_drum_available: false },
  { id: 'gs-8119', product_id: '', name: 'Deep Grey', code: '8119', hex: '#343434', is_drum_available: false },
  { id: 'gs-8441', product_id: '', name: 'Ivory M', code: '8441', hex: '#FFFFF0', is_drum_available: false },
  { id: 'gs-8172', product_id: '', name: 'New Grey', code: '8172', hex: '#BEBEBE', is_drum_available: false },
  { id: 'gs-8447', product_id: '', name: 'Royal Ivory', code: '8447', hex: '#FFFDD0', is_drum_available: false },
  { id: 'gs-8205', product_id: '', name: 'Black', code: '8205', hex: '#000000', is_drum_available: false },
  { id: 'gs-8185', product_id: '', name: 'Saz. Grey', code: '8185', hex: '#666666', is_drum_available: false },
  { id: 'gs-8408', product_id: '', name: 'Pale Grey', code: '8408', hex: '#D3D3D3', is_drum_available: false },
  { id: 'gs-8552', product_id: '', name: 'Metallic Golden', code: '8552', hex: '#D4AF37', is_drum_available: false },
  { id: 'gs-8538', product_id: '', name: 'Metallic Green', code: '8538', hex: '#228B22', is_drum_available: false },
  { id: 'gs-8206', product_id: '', name: 'Mixing Gold', code: '8206', hex: '#FFD700', is_drum_available: false },
  { id: 'gs-8545', product_id: '', name: 'Honda Red', code: '8545', hex: '#ED1C24', is_drum_available: false },
  { id: 'gs-8539', product_id: '', name: 'Metallic Blue', code: '8539', hex: '#0000FF', is_drum_available: false },
  { id: 'gs-8208', product_id: '', name: 'Metallic Brown', code: '8208', hex: '#A52A2A', is_drum_available: false },
  { id: 'gs-8201', product_id: '', name: 'Lt. Green Metal', code: '8201', hex: '#90EE90', is_drum_available: false },
  { id: 'gs-8536', product_id: '', name: 'Yamaha Red', code: '8536', hex: '#FF0000', is_drum_available: false },
  { id: 'gs-8564', product_id: '', name: 'Honda Red Sp', code: '8564', hex: '#D40000', is_drum_available: false },
  { id: 'gs-8209', product_id: '', name: 'Forest Green', code: '8209', hex: '#006400', is_drum_available: false },
  { id: 'gs-8535', product_id: '', name: 'Metallic Violet', code: '8535', hex: '#8B00FF', is_drum_available: false },
  { id: 'gs-8532', product_id: '', name: 'Aluminium Base', code: '8532', hex: '#D2D2D2', is_drum_available: false },
  { id: 'gs-8542', product_id: '', name: 'Hi.Sparkle Silver', code: '8542', hex: '#C0C0C0', is_drum_available: false },
  { id: 'gs-8534', product_id: '', name: 'Spk.Alu.U/Coat', code: '8534', hex: '#E5E4E2', is_drum_available: false },
  { id: 'gs-8543', product_id: '', name: 'Spk.Alu.Filter', code: '8543', hex: '#BCC6CC', is_drum_available: false },
  { id: 'gs-8601', product_id: '', name: 'Industrial White', code: '8601', hex: '#FFFFFF', is_drum_available: false },
  { id: 'gs-8602', product_id: '', name: 'Deep Black', code: '8602', hex: '#000000', is_drum_available: false },
  { id: 'gs-8603', product_id: '', name: 'Primer Grey', code: '8603', hex: '#9B9B9B', is_drum_available: false },
  { id: 'gs-8604', product_id: '', name: 'Primer Red Oxide', code: '8604', hex: '#6D1008', is_drum_available: false },
  { id: 'gs-8605', product_id: '', name: 'Satin Silver', code: '8605', hex: '#C0C0C0', is_drum_available: false },
  { id: 'gs-8606', product_id: '', name: 'Hammer Blue', code: '8606', hex: '#4B9CD3', is_drum_available: false },
  { id: 'gs-8607', product_id: '', name: 'Hammer Grey', code: '8607', hex: '#808080', is_drum_available: false },
  { id: 'gs-8608', product_id: '', name: 'Hammer Green', code: '8608', hex: '#008000', is_drum_available: false },
  { id: 'gs-8609', product_id: '', name: 'Clear Lacquer', code: '8609', hex: '#F0F8FF', is_drum_available: false },
  { id: 'gs-8610', product_id: '', name: 'Topaz Blue', code: '8610', hex: '#0070FF', is_drum_available: false },
  { id: 'gs-8611', product_id: '', name: 'Electric Green', code: '8611', hex: '#00FF00', is_drum_available: false },
  { id: 'gs-8612', product_id: '', name: 'Crimson Red', code: '8612', hex: '#DC143C', is_drum_available: false },
  { id: 'gs-8613', product_id: '', name: 'Deep Purple', code: '8613', hex: '#800080', is_drum_available: false },
  { id: 'gs-8614', product_id: '', name: 'Ochre Yellow', code: '8614', hex: '#DAA520', is_drum_available: false },
  { id: 'gs-8615', product_id: '', name: 'Tan Beige', code: '8615', hex: '#D2B48C', is_drum_available: false },
  { id: 'gs-8616', product_id: '', name: 'Slate Blue', code: '8616', hex: '#708090', is_drum_available: false },
  { id: 'gs-8617', product_id: '', name: 'Forest Brown', code: '8617', hex: '#5D4037', is_drum_available: false },
  { id: 'gs-8618', product_id: '', name: 'Ice White', code: '8618', hex: '#F0F8FF', is_drum_available: false },
];

export const GOBIS_CARMAN_SERIES_SHADES: Shade[] = [
  // Suzuki Shades
  { id: 'gc-383', product_id: '', name: 'New Grey', code: '383', hex: '#808080', is_drum_available: false },
  { id: 'gc-386', product_id: '', name: 'Steel Grey', code: '386', hex: '#778899', is_drum_available: false },
  { id: 'gc-373', product_id: '', name: 'Alto White', code: '373', hex: '#FFFFFF', is_drum_available: false },
  { id: 'gc-362', product_id: '', name: 'Gazelle Beige', code: '362', hex: '#D2B48C', is_drum_available: false },
  { id: 'gc-382', product_id: '', name: 'Aqua Jade', code: '382', hex: '#708D81', is_drum_available: false },
  { id: 'gc-361', product_id: '', name: 'Mid Blue', code: '361', hex: '#0000CD', is_drum_available: false },
  { id: 'gc-399', product_id: '', name: 'New Green', code: '399', hex: '#008000', is_drum_available: false },
  { id: 'gc-u26', product_id: '', name: 'White U26', code: 'U26', hex: '#FDFDFD', is_drum_available: false },
  { id: 'gc-377', product_id: '', name: 'Alto Red', code: '377', hex: '#FF0000', is_drum_available: false },
  { id: 'gc-04t', product_id: '', name: 'Pastel Blue', code: '04T', hex: '#ADD8E6', is_drum_available: false },
  { id: 'gc-348', product_id: '', name: 'Dark Blue', code: '348', hex: '#00008B', is_drum_available: false },
  { id: 'gc-347', product_id: '', name: 'Beige 347', code: '347', hex: '#F5F5DC', is_drum_available: false },
  { id: 'gc-372', product_id: '', name: 'Alto Green', code: '372', hex: '#228B22', is_drum_available: false },
  { id: 'gc-375', product_id: '', name: 'Lagoon Blue', code: '375', hex: '#20B2AA', is_drum_available: false },
  { id: 'gc-365', product_id: '', name: 'Slate Grey', code: '365', hex: '#708090', is_drum_available: false },
  { id: 'gc-06', product_id: '', name: 'Orange 06', code: '06', hex: '#FFA500', is_drum_available: false },
  { id: 'gc-367', product_id: '', name: 'Farina Red', code: '367', hex: '#DC143C', is_drum_available: false },
  { id: 'gc-557', product_id: '', name: 'Beige 557', code: '557', hex: '#F5F5DC', is_drum_available: false },
  { id: 'gc-y51', product_id: '', name: 'Yellow Y51', code: 'Y51', hex: '#FFFF00', is_drum_available: false },
  { id: 'gc-402', product_id: '', name: 'Greenish Blue', code: '402', hex: '#008B8B', is_drum_available: false },
  { id: 'gc-z2s', product_id: '', name: 'Silky Silver', code: 'Z2S', hex: '#C0C0C0', is_drum_available: false },
  { id: 'gc-z2z', product_id: '', name: 'Planet Gold', code: 'Z2Z', hex: '#D4AF37', is_drum_available: false },
  { id: 'gc-za4', product_id: '', name: 'Cool Beige', code: 'ZA4', hex: '#E1D9D1', is_drum_available: false },
  { id: 'gc-z6b', product_id: '', name: 'Reddish Silver', code: 'Z6B', hex: '#C4B4A4', is_drum_available: false },

  // Toyota Shades
  { id: 'gc-861', product_id: '', name: 'Light Blue', code: '861', hex: '#ADD8E6', is_drum_available: false },
  { id: 'gc-3e4', product_id: '', name: 'Hilux Red 3E4', code: '3E4', hex: '#ED1C24', is_drum_available: false },
  { id: 'gc-179', product_id: '', name: 'Grey 179', code: '179', hex: '#808080', is_drum_available: false },
  { id: 'gc-879', product_id: '', name: 'Dark Blue 879', code: '879', hex: '#000080', is_drum_available: false },
  { id: 'gc-3h4', product_id: '', name: 'Hilux Red 3H4', code: '3H4', hex: '#8B0000', is_drum_available: false },
  { id: 'gc-to3', product_id: '', name: 'Beige TO3', code: 'TO3', hex: '#F5F5DC', is_drum_available: false },
  { id: 'gc-4a4', product_id: '', name: 'Beige 4A4', code: '4A4', hex: '#EDE6D9', is_drum_available: false },
  { id: 'gc-8927', product_id: '', name: 'Brown 8927', code: '8927', hex: '#A52A2A', is_drum_available: false },
  { id: 'gc-474', product_id: '', name: 'Copper 474', code: '474', hex: '#B87333', is_drum_available: false },
  { id: 'gc-6m3', product_id: '', name: 'Silver Spruce', code: '6M3', hex: '#8E9B9A', is_drum_available: false },
  { id: 'gc-679', product_id: '', name: 'Light Green 679', code: '679', hex: '#90EE90', is_drum_available: false },
  { id: 'gc-183', product_id: '', name: 'Dark Bluish Grey', code: '183', hex: '#4B5320', is_drum_available: false },
  { id: 'gc-125', product_id: '', name: 'Silver 125', code: '125', hex: '#C0C0C0', is_drum_available: false },
  { id: 'gc-3k3', product_id: '', name: 'Red 3K3', code: '3K3', hex: '#FF0000', is_drum_available: false },
  { id: 'gc-3k9', product_id: '', name: 'Lt. Beige 3K9', code: '3K9', hex: '#F5F5DC', is_drum_available: false },

  // Honda Shades
  { id: 'gc-g78p', product_id: '', name: 'Sherwood Green', code: 'G78P', hex: '#006400', is_drum_available: false },
  { id: 'gc-bg28p', product_id: '', name: 'Tahitian Green', code: 'BG28P', hex: '#008080', is_drum_available: false },
  { id: 'gc-b62p', product_id: '', name: 'Captiva Blue', code: 'B62P', hex: '#0000FF', is_drum_available: false },
  { id: 'gc-yr505', product_id: '', name: 'Cashmere Silver', code: 'YR-505', hex: '#E2E2E2', is_drum_available: false },

  // General Shades
  { id: 'gc-704', product_id: '', name: 'Lemon Yellow', code: '704', hex: '#FFF44F', is_drum_available: false },
  { id: 'gc-799', product_id: '', name: 'Orange 799', code: '799', hex: '#FFA500', is_drum_available: false },
  { id: 'gc-741', product_id: '', name: 'Fridge Green', code: '741', hex: '#E0F0E0', is_drum_available: false },
  { id: 'gc-714', product_id: '', name: 'Silver Fine', code: '714', hex: '#C0C0C0', is_drum_available: false },
  { id: 'gc-705', product_id: '', name: 'Golden Yellow', code: '705', hex: '#FFD700', is_drum_available: false },
  { id: 'gc-796', product_id: '', name: 'Signal Red', code: '796', hex: '#FF0000', is_drum_available: false },
  { id: 'gc-710', product_id: '', name: 'Mixing Green', code: '710', hex: '#008000', is_drum_available: false },
  { id: 'gc-713', product_id: '', name: 'Silver Coarse', code: '713', hex: '#D3D3D3', is_drum_available: false },
  { id: 'gc-740', product_id: '', name: 'Vespa Blue', code: '740', hex: '#00008B', is_drum_available: false },
  { id: 'gc-703', product_id: '', name: 'Black 703', code: '703', hex: '#000000', is_drum_available: false },
  { id: 'gc-702', product_id: '', name: 'White 702', code: '702', hex: '#FFFFFF', is_drum_available: false },
  { id: 'gc-712', product_id: '', name: 'Auto Primer', code: '712', hex: '#808080', is_drum_available: false },
  { id: 'gc-795', product_id: '', name: 'Matt Black', code: '795', hex: '#2B2B2B', is_drum_available: false },
];

export const GOBIS_SILVERLINE_ENAMEL_SHADES: Shade[] = [
  // Standard Shades
  { id: 'gse-7059s', product_id: '', name: 'Antique White', code: '7059-S', hex: '#FAEBD7', is_drum_available: false },
  { id: 'gse-7048s', product_id: '', name: 'Soft Terracotta', code: '7048-S', hex: '#E3735E', is_drum_available: false },
  { id: 'gse-7002s', product_id: '', name: 'Off White', code: '7002-S', hex: '#FAF9F6', is_drum_available: false },
  { id: 'gse-7049s', product_id: '', name: 'Polish Brown', code: '7049-S', hex: '#7E4830', is_drum_available: false },
  { id: 'gse-7003s', product_id: '', name: 'Cream', code: '7003-S', hex: '#FFFDD0', is_drum_available: false },
  { id: 'gse-7004s', product_id: '', name: 'Champagne', code: '7004-S', hex: '#F7E7CE', is_drum_available: false },
  { id: 'gse-7011s', product_id: '', name: 'Red Oxide', code: '7011-S', hex: '#8B0000', is_drum_available: false },
  { id: 'gse-7050s', product_id: '', name: 'Brown', code: '7050-S', hex: '#8B4513', is_drum_available: false },
  { id: 'gse-7021s', product_id: '', name: 'Pale Cream', code: '7021-S', hex: '#FFF9E3', is_drum_available: false },
  { id: 'gse-7010s', product_id: '', name: 'Lemon', code: '7010-S', hex: '#FFF700', is_drum_available: false },
  { id: 'gse-7051s', product_id: '', name: 'Rose Pink', code: '7051-S', hex: '#FFC0CB', is_drum_available: false },
  { id: 'gse-7012s', product_id: '', name: 'Dark Brown', code: '7012-S', hex: '#3E2723', is_drum_available: false },
  { id: 'gse-7020s', product_id: '', name: 'Diyar', code: '7020-S', hex: '#63332D', is_drum_available: false },
  { id: 'gse-7013s', product_id: '', name: 'Golden Yellow', code: '7013-S', hex: '#FFCC00', is_drum_available: false },
  { id: 'gse-7052s', product_id: '', name: 'Hot Pink', code: '7052-S', hex: '#FF69B4', is_drum_available: false },
  { id: 'gse-7053s', product_id: '', name: 'Comet Blue', code: '7053-S', hex: '#3B5998', is_drum_available: false },
  { id: 'gse-7024s', product_id: '', name: 'Beige', code: '7024-S', hex: '#F5F5DC', is_drum_available: false },
  { id: 'gse-7009s', product_id: '', name: 'Orange', code: '7009-S', hex: '#FF8C00', is_drum_available: false },
  { id: 'gse-7060s', product_id: '', name: 'Country Cream', code: '7060-S', hex: '#FDF5E6', is_drum_available: false },
  { id: 'gse-7054s', product_id: '', name: 'Cornflower', code: '7054-S', hex: '#6495ED', is_drum_available: false },
  { id: 'gse-7018s', product_id: '', name: 'Sheesham', code: '7018-S', hex: '#6D4C41', is_drum_available: false },
  { id: 'gse-7016s', product_id: '', name: 'Signal Red', code: '7016-S', hex: '#E23D28', is_drum_available: false },
  { id: 'gse-7046s', product_id: '', name: 'Early Dawn', code: '7046-S', hex: '#E6E6FA', is_drum_available: false },
  { id: 'gse-7014s', product_id: '', name: 'Light Blue', code: '7014-S', hex: '#ADD8E6', is_drum_available: false },
  { id: 'gse-7028s', product_id: '', name: 'Coriander', code: '7028-S', hex: '#C4D300', is_drum_available: false },
  { id: 'gse-7030s', product_id: '', name: 'Golden Brown', code: '7030-S', hex: '#996515', is_drum_available: false },
  { id: 'gse-7047s', product_id: '', name: 'Cameo', code: '7047-S', hex: '#EFDECD', is_drum_available: false },
  { id: 'gse-7015s', product_id: '', name: 'Vivid Blue', code: '7015-S', hex: '#007FFF', is_drum_available: false },
  { id: 'gse-Middle-Blue', product_id: '', name: 'Middle Blue', code: '7061-S', hex: '#7ED4E6', is_drum_available: false },
  { id: 'gse-7065s', product_id: '', name: 'Gold', code: '7065-S', hex: '#FFD700', is_drum_available: false },
  { id: 'gse-7022s', product_id: '', name: 'Royal Green', code: '7022-S', hex: '#004225', is_drum_available: false },
  { id: 'gse-7058s', product_id: '', name: 'Dark Grey', code: '7058-S', hex: '#555555', is_drum_available: false },
  { id: 'gse-7062s', product_id: '', name: 'Royal Blue', code: '7062-S', hex: '#002366', is_drum_available: false },
  { id: 'gse-7064s', product_id: '', name: 'Grey Green', code: '7064-S', hex: '#5E716A', is_drum_available: false },
  { id: 'gse-7055s', product_id: '', name: 'Mauve', code: '7055-S', hex: '#E0B0FF', is_drum_available: false },
  { id: 'gse-7056s', product_id: '', name: 'White Green', code: '7056-S', hex: '#F0FFF0', is_drum_available: false },
  { id: 'gse-7017s', product_id: '', name: 'Ash White', code: '7017-S', hex: '#B2BEB5', is_drum_available: false },
  { id: 'gse-7025s', product_id: '', name: 'Sea Green', code: '7025-S', hex: '#2E8B57', is_drum_available: false },
  { id: 'gse-7027s', product_id: '', name: 'Oyster', code: '7027-S', hex: '#EAE0C8', is_drum_available: false },
  { id: 'gse-7066s', product_id: '', name: 'Light Green', code: '7066-S', hex: '#90EE90', is_drum_available: false },
  { id: 'gse-7026s', product_id: '', name: 'Pumice', code: '7026-S', hex: '#D2D3CE', is_drum_available: false },
  { id: 'gse-7057s', product_id: '', name: 'Adams Green', code: '7057-S', hex: '#879274', is_drum_available: false },
  { id: 'gse-7023s', product_id: '', name: 'Smoke Grey', code: '7023-S', hex: '#708284', is_drum_available: false },
  { id: 'gse-7007s', product_id: '', name: 'Spring Green', code: '7007-S', hex: '#00FF7F', is_drum_available: false },
  { id: 'gse-7063s', product_id: '', name: 'Court Grey', code: '7063-S', hex: '#D3D3D3', is_drum_available: false },
  { id: 'gse-7019s', product_id: '', name: 'Emerald', code: '7019-S', hex: '#50C878', is_drum_available: false },
  { id: 'gse-7001s', product_id: '', name: 'Brilliant White', code: '7001-S', hex: '#FFFFFF', is_drum_available: false },
  { id: 'gse-7045s', product_id: '', name: 'Black', code: '7045-S', hex: '#000000', is_drum_available: false },

  // Metallic Finish Shades
  { id: 'gse-7071s', product_id: '', name: 'Champ. Silver', code: '7071-S', hex: '#B8B799', is_drum_available: false },
  { id: 'gse-7072s', product_id: '', name: 'Champagne Metallic', code: '7072-S', hex: '#D7C4A5', is_drum_available: false },
  { id: 'gse-7077s', product_id: '', name: 'Iceland Blue', code: '7077-S', hex: '#C1D3E1', is_drum_available: false },
  { id: 'gse-7073s', product_id: '', name: 'Gold Valley', code: '7073-S', hex: '#FFD700', is_drum_available: false },
  { id: 'gse-7078s', product_id: '', name: 'Shiny Green', code: '7078-S', hex: '#00FF00', is_drum_available: false },
  { id: 'gse-7074s', product_id: '', name: 'Copper', code: '7074-S', hex: '#B87333', is_drum_available: false },
  { id: 'gse-7079s', product_id: '', name: 'Green Gold', code: '7079-S', hex: '#C5B358', is_drum_available: false },
  { id: 'gse-7075s', product_id: '', name: 'Dark Brown Metallic', code: '7075-S', hex: '#5D4037', is_drum_available: false },
  { id: 'gse-7080s', product_id: '', name: 'Lush Green', code: '7080-S', hex: '#008000', is_drum_available: false },
  { id: 'gse-7076s', product_id: '', name: 'Rose Pack', code: '7076-S', hex: '#FF007F', is_drum_available: false },
  { id: 'gse-7081s', product_id: '', name: 'Fine Silver', code: '7081-S', hex: '#C0C0C0', is_drum_available: false },
];

export const GOBIS_SILVERLINE_EMULSION_SHADES: Shade[] = [
  { id: 'gse-1404s', product_id: '', name: 'Color White', code: '1404-S', hex: '#F5F5F5', is_drum_available: false },
  { id: 'gse-1402s', product_id: '', name: 'Magnolia', code: '1402-S', hex: '#F3E5AB', is_drum_available: false },
  { id: 'gse-1452s', product_id: '', name: 'Moon Flower', code: '1452-S', hex: '#F8F8FF', is_drum_available: false },
  { id: 'gse-1455s', product_id: '', name: 'Peach', code: '1455-S', hex: '#FFE5B4', is_drum_available: false },
  { id: 'gse-1473s', product_id: '', name: 'Cameo', code: '1473-S', hex: '#EFDECD', is_drum_available: false },
  { id: 'gse-1406s', product_id: '', name: 'Twilight', code: '1406-S', hex: '#E4E0E9', is_drum_available: false },
  { id: 'gse-1401s', product_id: '', name: 'Off White', code: '1401-S', hex: '#FAF9F6', is_drum_available: false },
  { id: 'gse-1407s', product_id: '', name: 'Cockleshell', code: '1407-S', hex: '#FFCBA4', is_drum_available: false },
  { id: 'gse-1409s', product_id: '', name: 'Ivory Silk', code: '1409-S', hex: '#F2E5D7', is_drum_available: false },
  { id: 'gse-1412s', product_id: '', name: 'Peach Goddess', code: '1412-S', hex: '#FFDAB9', is_drum_available: false },
  { id: 'gse-1458s', product_id: '', name: 'Ash White', code: '1458-S', hex: '#B2BEB5', is_drum_available: false },
  { id: 'gse-1417s', product_id: '', name: 'Romantic', code: '1417-S', hex: '#FBD7D1', is_drum_available: false },
  { id: 'gse-1410s', product_id: '', name: 'Honey Milk', code: '1410-S', hex: '#F1E9D2', is_drum_available: false },
  { id: 'gse-1471s', product_id: '', name: 'Zephyr', code: '1471-S', hex: '#D0D0D0', is_drum_available: false },
  { id: 'gse-1411s', product_id: '', name: 'Badami', code: '1411-S', hex: '#E9DCC9', is_drum_available: false },
  { id: 'gse-1408s', product_id: '', name: 'White Pepper', code: '1408-S', hex: '#EAE0C8', is_drum_available: false },
  { id: 'gse-1403s', product_id: '', name: 'Soft Silk', code: '1403-S', hex: '#F2F0E6', is_drum_available: false },
  { id: 'gse-1405s', product_id: '', name: 'Cream', code: '1405-S', hex: '#FFFDD0', is_drum_available: false },
  { id: 'gse-1470s', product_id: '', name: 'Sand Stone', code: '1470-S', hex: '#C2B280', is_drum_available: false },
  { id: 'gse-1415s', product_id: '', name: 'Wild Earl', code: '1415-S', hex: '#D2B48C', is_drum_available: false },
  { id: 'gse-1413s', product_id: '', name: 'Desert Dawn', code: '1413-S', hex: '#F4A460', is_drum_available: false },
  { id: 'gse-1469s', product_id: '', name: 'Pink', code: '1469-S', hex: '#FFC0CB', is_drum_available: false },
  { id: 'gse-1425s', product_id: '', name: 'Lime Light', code: '1425-S', hex: '#E3F9A6', is_drum_available: false },
  { id: 'gse-1436s', product_id: '', name: 'Sea Wind', code: '1436-S', hex: '#B0E0E6', is_drum_available: false },
  { id: 'gse-1422s', product_id: '', name: 'Health Violet', code: '1422-S', hex: '#D8BFD8', is_drum_available: false },
  { id: 'gse-1467s', product_id: '', name: 'Tea Rose', code: '1467-S', hex: '#F4C2C2', is_drum_available: false },
  { id: 'gse-1447s', product_id: '', name: 'Cherry Blossom Pink', code: '1447-S', hex: '#FFB7C5', is_drum_available: false },
  { id: 'gse-1424s', product_id: '', name: 'Fresh Green', code: '1424-S', hex: '#90EE90', is_drum_available: false },
  { id: 'gse-1438s', product_id: '', name: 'Ice Age', code: '1438-S', hex: '#F0F8FF', is_drum_available: false },
  { id: 'gse-1464s', product_id: '', name: 'Ice Grey', code: '1464-S', hex: '#D3D3D3', is_drum_available: false },
  { id: 'gse-1416s', product_id: '', name: 'Hopsack', code: '1416-S', hex: '#B08D57', is_drum_available: false },
  { id: 'gse-1418s', product_id: '', name: 'Deep Pink', code: '1418-S', hex: '#FF1493', is_drum_available: false },
  { id: 'gse-1427s', product_id: '', name: 'Pastel Green', code: '1427-S', hex: '#77DD77', is_drum_available: false },
  { id: 'gse-1459s', product_id: '', name: 'Blue', code: '1459-S', hex: '#0000FF', is_drum_available: false },
  { id: 'gse-Dove-Grey', product_id: '', name: 'Dove Grey', code: '1468-S', hex: '#6D9BC3', is_drum_available: false },
  { id: 'gse-1432s', product_id: '', name: 'Citrus Yellow', code: '1432-S', hex: '#F0E130', is_drum_available: false },
  { id: 'gse-1430s', product_id: '', name: 'Electric Blue', code: '1430-S', hex: '#7DF9FF', is_drum_available: false },
  { id: 'gse-1428s', product_id: '', name: 'Pink Violet', code: '1428-S', hex: '#E0B0FF', is_drum_available: false },
  { id: 'gse-1414s', product_id: '', name: 'Fresh Orange', code: '1414-S', hex: '#FF8C00', is_drum_available: false },
  { id: 'gse-1429s', product_id: '', name: 'Carnival Pink', code: '1429-S', hex: '#FF69B4', is_drum_available: false },
  { id: 'gse-1420s', product_id: '', name: 'Bright Red', code: '1420-S', hex: '#FF0000', is_drum_available: false },
  { id: 'gse-1462s', product_id: '', name: 'Purple', code: '1462-S', hex: '#800080', is_drum_available: false },
  { id: 'gse-1431', product_id: '', name: 'Winter Willow', code: '1431', hex: '#E1EBDA', is_drum_available: false },
  { id: 'gse-1419s', product_id: '', name: 'Swiss Miss', code: '1419-S', hex: '#F3E5AB', is_drum_available: false },
  { id: 'gse-1472s', product_id: '', name: 'Forest Green', code: '1472-S', hex: '#228B22', is_drum_available: false },
  { id: 'gse-1439s', product_id: '', name: 'Blue Heaven', code: '1439-S', hex: '#87CEEB', is_drum_available: false },
  { id: 'gse-1434s', product_id: '', name: 'Whisper', code: '1434-S', hex: '#F3E5AB', is_drum_available: false },
  { id: 'gse-1426s', product_id: '', name: 'Classical Tint', code: '1426-S', hex: '#FDF5E6', is_drum_available: false },
  { id: 'gse-1463s', product_id: '', name: 'Green Summit', code: '1463-S', hex: '#5E7D7E', is_drum_available: false },
  { id: 'gse-1435s', product_id: '', name: 'Goose Wing', code: '1435-S', hex: '#BAC4C8', is_drum_available: false },
  { id: 'gse-1466s', product_id: '', name: 'Parasol', code: '1466-S', hex: '#EFDECD', is_drum_available: false },
  { id: 'gse-1433s', product_id: '', name: 'Apricot', code: '1433-S', hex: '#FBCEB1', is_drum_available: false },
  { id: 'gse-1465s', product_id: '', name: 'Terracotta', code: '1465-S', hex: '#E2725B', is_drum_available: false },
  { id: 'gse-1421s', product_id: '', name: 'Chocolate', code: '1421-S', hex: '#7B3F00', is_drum_available: false },
];
